### ISSUE TITLE
`scv.utils.merge` UnboundLocalError: local variable 'id_length' referenced before assignment

### ISSUE THREAD

**Issue by danli349** [theislab/scvelo#1031] opened 2023-03-29 16:04 UTC
Hello 

Can someone please help me with how should I fix this error?

```
import scvelo as scv
print(scv.__version__)
```
0.2.5

```
adata_dKO3 = scv.utils.merge(adata_dKO2, ldata_dKO)
```

```
--------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[158], line 1
----> 1 adata_dKO3 = scv.utils.merge(adata_dKO2, ldata_dKO)

File ~/miniconda3/lib/python3.8/site-packages/scvelo/core/_anndata.py:526, in merge(adata, ldata, copy, **kwargs)
    524 if "id_length" in kwargs:
    525     id_length = kwargs.get("id_length")
--> 526 clean_obs_names(adata, id_length=id_length)
    527 clean_obs_names(ldata, id_length=id_length)
    528 common_obs = adata.obs_names.intersection(ldata.obs_names)

UnboundLocalError: local variable 'id_length' referenced before assignment
```
Thanks a lot.

**Comment by WeilerP** [comment] 2023-03-29 16:29
Duplicate of #983. Please search among issues before opening a new one.

**Closed by WeilerP** 2023-03-29 16:29 UTC
Labels: bug, duplicate
