### ISSUE TITLE
High unspliced ratio

### ISSUE THREAD

**Issue by brucewayne521** [theislab/scvelo#949] opened 2022-10-26 13:51 UTC
Hello！
Really great package for RNA velocity analysis.
When I checked the proportion of spliced/unspliced counts, using _scv.pl.proportions(adata)_ , I found the ratio of unspliced counts is surprisingly high:
![image](https://user-images.githubusercontent.com/32565838/198040539-46e70d5c-340f-4842-a13b-bdddd717b131.png)
I don't know if this is normal or there is something wrong with my pre-process?
I did my counting with Cellranger 7.0.1, and generation of the loom file with velocyto 0.17.
![image](https://user-images.githubusercontent.com/32565838/198044056-10c9c474-9ec6-47fa-b483-d31deb1d0142.png)

**Comment by WeilerP** [comment] 2022-10-26 14:00
Not a code related issue and duplicate of several discussion. @brucewayne521, please have a look at the relevant discussions.

**Closed by WeilerP** 2022-10-26 14:00 UTC
Labels: duplicate
