### ISSUE TITLE
Plot error (when using cellrank, with pandas >=2)

### ISSUE THREAD

**Issue by dawe** [theislab/scvelo#1060] opened 2023-05-16 14:34 UTC
I was working with `cellrank`, which builds on `scvelo`, on a fresh conda environment. I've noticed that `g_fwd.plot_macrostates()` doesn't work if `same_plot=True`.

<details>

<summary> Error output </summary>

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[170], line 1
----> 1 g_fwd.plot_macrostates()

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/cellrank/tl/estimators/mixins/_utils.py:415, in register_plotter.<locals>.wrapper(wrapped, instance, args, kwargs)
    412 else:
    413     _colors = getattr(instance, colors, None)
--> 415 return wrapped(
    416     *args,
    417     _data=data,
    418     _colors=_colors,
    419     _title=attr,
    420     discrete=disc,
    421     **kwargs,
    422 )

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/scanpy/_utils/__init__.py:119, in deprecated_arg_names.<locals>.decorator.<locals>.func_wrapper(*args, **kwargs)
    117 # reset filter
    118 warnings.simplefilter('default', DeprecationWarning)
--> 119 return func(*args, **kwargs)

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/cellrank/tl/estimators/mixins/_utils.py:342, in _plot_dispatcher(self, states, color, discrete, mode, time_key, same_plot, title, cmap, **kwargs)
    331 if discrete:
    332     return _plot_discrete(
    333         self,
    334         states=states,
   (...)
    339         **kwargs,
    340     )
--> 342 return _plot_continuous(
    343     self,
    344     states=states,
    345     color=color,
    346     mode=mode,
    347     time_key=time_key,
    348     same_plot=same_plot,
    349     title=title,
    350     cmap=cmap,
    351     **kwargs,
    352 )

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/cellrank/tl/estimators/mixins/_utils.py:278, in _plot_continuous(self, _data, _colors, _title, states, color, mode, time_key, title, same_plot, cmap, **kwargs)
    275     kwargs.setdefault("perc", [0, 95])
    276     _ = kwargs.pop("color_gradients", None)
--> 278 scv.pl.scatter(
    279     self.adata,
    280     title=title,
    281     color_map=cmap,
    282     **kwargs,
    283 )

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/scvelo/plotting/scatter.py:274, in scatter(adata, basis, x, y, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_loc_lines, legend_fontsize, legend_fontweight, legend_fontoutline, legend_align_text, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, add_density, add_assignments, add_linfit, add_polyfit, add_rug, add_text, add_text_pos, add_margin, add_outline, outline_width, outline_color, n_convolve, smooth, normalize_data, rescale_color, color_gradients, dpi, frameon, zorder, ncols, nrows, wspace, hspace, show, save, ax, **kwargs)
    266 mkwargs.pop("color")
    267 ax = scatter(
    268     adata,
    269     color="grey",
   (...)
    272     **get_kwargs(scatter_kwargs, {"alpha": 0.05}),
    273 )  # background
--> 274 ax = scatter(
    275     adata,
    276     color=color,
    277     ax=ax,
    278     **mkwargs,
    279     **get_kwargs(scatter_kwargs, {"s": 0}),
    280 )  # set legend
    281 sorted_idx = np.argsort(vals, 1)[:, ::-1][:, :2]
    282 for id0 in range(len(names)):

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/scvelo/plotting/scatter.py:668, in scatter(adata, basis, x, y, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_loc_lines, legend_fontsize, legend_fontweight, legend_fontoutline, legend_align_text, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, add_density, add_assignments, add_linfit, add_polyfit, add_rug, add_text, add_text_pos, add_margin, add_outline, outline_width, outline_color, n_convolve, smooth, normalize_data, rescale_color, color_gradients, dpi, frameon, zorder, ncols, nrows, wspace, hspace, show, save, ax, **kwargs)
    666     if not (add_outline is None or g_bool is None):
    667         groups = add_outline
--> 668     set_legend(
    669         adata,
    670         ax,
    671         color,
    672         legend_loc,
    673         scatter_array,
    674         legend_fontweight,
    675         legend_fontsize,
    676         legend_fontoutline,
    677         legend_align_text,
    678         groups,
    679     )
    680 if add_density:
    681     plot_density(x, y, add_density, ax=ax)

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/scvelo/plotting/utils.py:555, in set_legend(adata, ax, value_to_plot, legend_loc, scatter_array, legend_fontweight, legend_fontsize, legend_fontoutline, legend_align_text, groups)
    553     legend_fontoutline = 1
    554 obs_vals = adata.obs[value_to_plot]
--> 555 obs_vals.cat.categories = obs_vals.cat.categories.astype(str)
    556 color_keys = adata.uns[f"{value_to_plot}_colors"]

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/pandas/core/base.py:178, in NoNewAttributesMixin.__setattr__(self, key, value)
    172 if getattr(self, "__frozen", False) and not (
    173     key == "_cache"
    174     or key in type(self).__dict__
    175     or getattr(self, key, None) is not None
    176 ):
    177     raise AttributeError(f"You cannot add any new attribute '{key}'")
--> 178 object.__setattr__(self, key, value)

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/pandas/core/accessor.py:99, in PandasDelegate._add_delegate_accessors.<locals>._create_delegator_property.<locals>._setter(self, new_values)
     98 def _setter(self, new_values):
---> 99     return self._delegate_property_set(name, new_values)

File ~/miniforge3/envs/may23/lib/python3.10/site-packages/pandas/core/arrays/categorical.py:2460, in CategoricalAccessor._delegate_property_set(self, name, new_values)
   2459 def _delegate_property_set(self, name, new_values):
-> 2460     return setattr(self._parent, name, new_values)

AttributeError: can't set attribute 'categories'
```

</details>

For the time being I've patched my local install at line 555 (which now is https://github.com/theislab/scvelo/blob/3b9fb0706fad9b49cb2e399b0326ae4b05042c24/scvelo/plotting/utils.py#LL644C66-L644C66)

```
obs_vals = obs_vals.cat.set_categories(obs_vals.cat.categories.astype(str)) 
```

<details> <summary> Versions </summary>

```pytb
scvelo==0.2.5  scanpy==1.9.3  anndata==0.9.1  loompy==3.0.6  numpy==1.23.5  scipy==1.10.1  matplotlib==3.7.1  sklearn==1.2.2  pandas==2.0.0   
```

</details>

**Comment by WeilerP** [comment] 2023-05-16 14:38
Closing as duplicate of #1037.

**Closed by WeilerP** 2023-05-16 14:38 UTC
Labels: bug
