### ISSUE TITLE
Gene expression is not shown on scatter plot

### ISSUE THREAD

**Issue by jinyoung5484** [theislab/scvelo#438] opened 2021-05-03 17:19 UTC
Hello, I am working on a single cell RNA seq data for neutrophil where I previously explored that certain genes are expressed on clusters through Seurat. When I converted this data to loom file and ran scVelo, Genes that were expressed on Seurat are not expressed on scVelo. Does anyone know why this happens?

I tried with this function to see expression of a gene. --> scv.pl.velocity(adata, gene, dpi = 300)
...

This is the adata that I used after normalization and velocity graph.

AnnData object with n_obs × n_vars = 4154 × 33538
    obs: 'Clusters', '_X', '_Y', 'n_counts', 'velocity_self_transition', 'louvain'
    var: 'Accession', 'Chromosome', 'End', 'Start', 'Strand', 'gene_count_corr', 'velocity_gamma', 'velocity_qreg_ratio', 'velocity_r2', 'velocity_genes', 'fit_alpha', 'fit_beta', 'fit_gamma', 'fit_t_', 'fit_scaling', 'fit_std_u', 'fit_std_s', 'fit_likelihood', 'fit_u0', 'fit_s0', 'fit_pval_steady', 'fit_steady_u', 'fit_steady_s', 'fit_variance', 'fit_alignment_scaling', 'fit_r2'
    uns: 'pca', 'neighbors', 'velocity_params', 'velocity_graph', 'velocity_graph_neg', 'louvain', 'umap', 'recover_dynamics'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs', 'loss'
    layers: 'matrix', 'ambiguous', 'spliced', 'unspliced', 'Ms', 'Mu', 'velocity', 'variance_velocity', 'fit_t', 'fit_tau', 'fit_tau_', 'velocity_u'
    obsp: 'distances', 'connectivities'
...

#### Versions:

scvelo==0.2.3  scanpy==1.7.1  anndata==0.7.5  loompy==3.0.6  numpy==1.19.1  scipy==1.4.0  matplotlib==3.4.1  sklearn==0.21.3  pandas==1.2.3
>

**Comment by WeilerP** [comment] 2021-05-08 09:48
@jinyoung5484, is it possible for you to share the plot you are generating using `scv.pl.velocity` and the one you were expecting?

**Comment by jinyoung5484** [comment] 2021-05-09 16:08
I attached MPO expression from seurat and scVelo at the bottom. 

![MPO_expression_seurat](https://user-images.githubusercontent.com/63210104/117579044-2e7b3280-b0bf-11eb-9f55-17b1d55149d3.png)
[scvelo_MPO_expression_scVelo.pdf](https://github.com/theislab/scvelo/files/6447950/scvelo_MPO_expression_scVelo.pdf)

**Comment by WeilerP** [comment] 2021-05-10 05:05
Okay, I see what you mean.
1. Just to make sure the problem is not related to the `loom` conversion: Did you check that the gene is expressed after importing the data and prior to running any preprocessing or analysis steps?
2. Could you please provide a code snippet of the steps you apply so that have a clear picture of what your pipeline looks like?
3. The plot created in R shows the UMAP embedding. What does the UMAP embedding collared by MPO expression look like after preprocessing in `scvelo`?

**Comment by WeilerP** [comment] 2021-05-28 13:12
@jinyoung5484, any update on this? I am closing this for now. Feel free to reopen the issue if it has not been resolved.

**Closed by WeilerP** 2021-05-28 13:12 UTC
Labels: bug

**Comment by stefanpeidli** [comment] 2021-08-17 13:04
Hi Philipp,
I've seen this error multiple times in the past. For me, it seems to happen when your adata.X is not a sparse csr matrix anymore (e.g. after using combat). Conversion of adata.X to a csr_matrix solved the issue for me.
-Stefan
