### ISSUE TITLE
calling  scv.utils.merge generates "UnboundLocalError: local variable 'id_length' referenced before assignment"

### ISSUE THREAD

**Issue by coolmak32** [theislab/scvelo#989] opened 2023-01-29 22:58 UTC
Hi Theislab!

I am trying to merge h5ad file with a loom file generated by velocyto ran on the cell ranger output directory. The h5ad file I have generated by extracting information for a Seurat object using scanpy using this tutorial (https://smorabit.github.io/tutorials/8_velocyto/).  

By calling ccv.utils.merge command get the above mentioned error. I am not a python expert but all the reading that I have done points out that the local variable somewhere in the script is being called before it ever being assigned. But to python-handicapped brain just mere understanding of this techanicallity does not provide a work- around. Can you please suggest me a solution of what might be going wrong. please see below my commands:

_import scvelo as scv
import scanpy as sc
import anndata as ad
import numpy as np
import pandas as pd
from scipy import io
from scipy.sparse import coo_matrix, csr_matrix
import os
import collections.abc
collections.Iterable = collections.abc.Iterable
collections.Mapping = collections.abc.Mapping
collections.MutableSet = collections.abc.MutableSet
collections.MutableMapping = collections.abc.MutableMapping
import cellrank as cr
scv.settings.verbosity = 3
scv.settings.set_figure_params('scvelo', facecolor='white', dpi=100, frameon=False)
cr.settings.verbosity = 2
ldata = scv.read('cellRanger.loom', cache=True)
scv.pp.remove_duplicate_cells(ldata)
ldata.var_names_make_unique()
barcodes = [bc.split(':')[1] for bc in ldata.obs.index.tolist()]
barcodes = [bc[0:len(bc)-1] + '_10' for bc in barcodes]
ldata.obs.index = barcodes
adata = sc.read_h5ad('skin1.h5ad')
adata = scv.utils.merge(adata, ldata)
UnboundLocalError                         Traceback (most recent call last)
Cell In[22], line 1
----> 1 adata = scv.utils.merge(adata, ldata)

File ~/miniconda3/lib/python3.10/site-packages/scvelo/core/_anndata.py:526, in merge(adata, ldata, copy, **kwargs)
    524 if "id_length" in kwargs:
    525     id_length = kwargs.get("id_length")
--> 526 clean_obs_names(adata, id_length=id_length)
    527 clean_obs_names(ldata, id_length=id_length)
    528 common_obs = adata.obs_names.intersection(ldata.obs_names)

UnboundLocalError: local variable 'id_length' referenced before assignment_

I tried to read about kwargs and still confused to pass this command defining kwargs may be as id_length?

Thank you for your help already.

**Comment by coolmak32** [comment] 2023-01-29 23:15
running this command "ldata = scv.read_loom('cellRanger.loom')" 

rather than

 "ldata = scv.read('cellRanger.loom', cache=True)"

did not throw the error. But then it is okay to run this command or is it messing up something in the backend?

**Comment by coolmak32** [comment] 2023-01-29 23:35
running these two commands before merging did solve the issue. 

scv.utils.clean_obs_names(adata)
scv.utils.clean_obs_names(ldata)

adata = scv.utils.merge(adata, ldata)

**Comment by WeilerP** [comment] 2023-01-30 06:15
Duplicate of #983. Please search open issues first, do not open a duplicate one, and use the issue template for bugs.

**Closed by WeilerP** 2023-01-30 06:15 UTC

**Comment by WeilerP** [comment] 2023-05-17 10:36
Still a duplicate of #983. Also, you will probably want to downgrade Pandas (see #1037).

**Comment by mdm247** [comment] 2023-05-17 15:18
> Still a duplicate of #983. Also, you will probably want to downgrade Pandas (see #1037).

Hi, thanks for looking into this. I'm probably missing something obvious. I did look at 983 and 990 before posting, but running clean_obs_names() gets rid of the error. However, the merge is not correct - as you can see, it drops most of the cells (2052 final instead of 43079).

**Comment by tsega2130** [comment] 2023-06-05 00:00
Hi, not a part of the dev team but faced a similar issue. What worked for me was deleting the cache folder from previous runs or setting `cache = False` when loading in the initial loom files. Also mentioned in #366.

Hope this helps

**Comment by feanaros** [comment] 2023-09-24 01:49
Hi, did you dove It?  @mdm247

**Comment by PietroD** [comment] 2023-10-18 13:26
> > Still a duplicate of #983. Also, you will probably want to downgrade Pandas (see #1037).
> 
> Hi, thanks for looking into this. I'm probably missing something obvious. I did look at 983 and 990 before posting, but running clean_obs_names() gets rid of the error. However, the merge is not correct - as you can see, it drops most of the cells (2052 final instead of 43079).

Same here. Have you found a solution?

**Comment by Roger-GOAT** [comment] 2023-10-20 16:36
The old vesion of scvelo would not get this error and did not need to scv.utils.clean_obs_names(), and get the right number of the obs_names. But right now, it shows "local variable 'id_length' referenced before assignment". And after scv.utils.clean_obs_names(), the number is not right! @WeilerP I read related issue and the pandas is 1.5.3

**Comment by tsa4002** [comment] 2023-10-20 17:03
Not part of the dev team but I've faced this issue before. scv.utils.clean_obs_names() shouldn't need to be called. To properly do a merge without using scv.utils.clean_obs_names, its very important to add a column to the metadata of your seurat object before importing it. 

This column should be the cell barcodes with a suffix of the cell's corresponding loom batch (Ex: AAACCCAAGATGTTGA-1-0). Loom batch is determined by the zero order index the loom files will be loaded in. Do **NOT** have sample prefixes. That causes interference when the seurat metadata is merged with the loom files.

And when you're loading in each sample's loom files, the order **must** correspond with that sample's suffix set in step 1. Then I renamed the barcodes to allow intersection.

```python
#Rename barcodes for each SM loom sample to intersect with adata
loom_files = [ldata1, ldata2, ldata3, ldata4, ldata5, ldata6]

for i in loom_files:
    barcodes = [bc.split(':')[1] for bc in i.obs.index.tolist()]
    barcodes = [bc[0:len(bc)-1] + '-1' for bc in barcodes]
    i.obs.index = barcodes
    i.var_names_make_unique()
``` 

 @LikiTan mentioned something similar [in this issue](https://github.com/theislab/scvelo/issues/983#issuecomment-1579827818). 
 
 @WeilerP This isn't a duplicate of the main issue in #983 and given the amount of people who have faced it, would be helpful to have an official response from the dev team in case my approach is missing something. 
 
 Thanks!
