### ISSUE TITLE
dynamic_model dimensionality problem 

### ISSUE THREAD

**Issue by akattapuram-insitro** [theislab/scvelo#1106] opened 2023-07-31 18:10 UTC
dimensions seem to be non-conformable when scaling dm.alpha, beta, gamma, t, tau, pars 

.pars[:3] is a numpy array of dimension (3,10) (in our dataset) whereas the other variables are floats. Safer to scale individually to catch edge cases such as this one. 

```
if dm is not None and dm.recoverable:
        dm.m = m[idx]

        #dm.alpha, dm.beta, dm.gamma, dm.pars[:3] = (                                                                                                   
        #    np.array([dm.alpha, dm.beta, dm.gamma, dm.pars[:3]]) / dm.m[-1]                                                                            
        #)                                                                                                                                              

        dm.alpha=dm.alpha/dm.m[-1]
        dm.beta=dm.beta/dm.m[-1]
	dm.gamma=dm.gamma/dm.m[-1]
        dm.pars[:3]=dm.pars[:3]/dm.m[-1]


        #dm.t, dm.tau, dm.t_, dm.pars[4] = (                                                                                                            
        #    np.array([dm.t, dm.tau, dm.t_, dm.pars[4]]) * dm.m[-1]                                                                                     
	#)                                                                                                                                              
        dm.t=dm.t*dm.m[-1]
        dm.tau=dm.tau*dm.m[-1]
        dm.t_=dm.t_*dm.m[-1]
        dm.pars[4]=dm.pars[4]*dm.m[-1]
```
(the commented out lines are what's in scvelo, the non-commented out lines are the proposed fix)

**Comment by WeilerP** [comment] 2023-07-31 18:19
Duplicate of #1087. Please check open/resolved issues and PRs before opening new ones and use the provided issue templates.

**Closed by WeilerP** 2023-07-31 18:19 UTC
Labels: bug, duplicate
