### ISSUE TITLE
Specifying start / end cell (Specify root_cells and end_point)

### ISSUE THREAD

**Issue by zakiF** [theislab/scvelo#162] opened 2020-02-26 12:44 UTC
Hi,

Many thanks for the scVeloo toolkit and the github tutorials. Pretaining to issue #157 #112, I also encountered that the direction goes opposite to what is expected (Day 7 > Day 5 > Day 3) rather than (Day 3 > Day 5 > Day 7). I tried some of the suggestion mentioned in the others thread mainy the different mode steady_state, stochastic, dynamical, but it gives very simillar results.

In one of the comments @VolkerBergen you mentioned 

> The roots may have already been computed e.g. via tl.terminal_states or given by the user via adata.uns[root_key], otherwise it is computed here internally.

So at the moment, both pseudotime (Figure below 'velocity pseudotime') and direction is going in the opposite direction. Therefore I was wondering if its possible to set the root_cells? And would this hopefully invert the peudotime and direction...

```
scv.pl.scatter(mdata, color='velocity_pseudotime'
scv.tl.terminal_states(mdata)
scv.pl.scatter(mdata, color=['root_cells', 'end_points''])
```

![Picture1](https://user-images.githubusercontent.com/33129835/75345743-41785d00-5895-11ea-9cd4-2a2dbd1b1a29.png)

In #114 you did mention 

> We will work out a more robust way of confidently assigning root cells soon. For now, you can either store a root cell in` adata.uns['iroot'] `and use root_key='iroot', or you can constrain the `adata.obs['root_cells']` to the bottom cells.

Does the `iroot` refer to one cell or a cluster/group of cells?

Best
Zaki

**Comment by VolkerBergen** [comment] 2020-02-26 13:03
Hi Zaki,

nice example and seems to exactly fall into this fundamental limitation where unspliced-to-spliced relation ends up in a straight line instead of a full curvature, yielding an unidentifiability issue. As mentioned in previous issues, you can specify a root which is then used as prior in the dynamical model. This is yet under development in https://github.com/theislab/scvelo/pull/144 and should be usable by next week. 

This issue is fundamental and not dealt with appropriately in any existing model. It can only be solved with prior information (such as first experimental timepoint or a user-specified progenitor population). We are currently elaborating this point in great detail for the revision of the manuscript.

**Comment by zakiF** [comment] 2020-02-26 13:06
Hi Volker,

Thanks for the reply, so just clarify at the moment it is **not** possible to specifiy a root? But hopefully it would be added sometime next week :)

Many thanks again

**Comment by VolkerBergen** [comment] 2020-02-26 13:13
Yes, it is not yet possible, but should be doable (at least some Beta version) by next week. 

Will also talk about this limitation in detail at [SCB](https://coursesandconferences.wellcomegenomecampus.org/our-events/single-cell-biology-2020/).

**Comment by zakiF** [comment] 2020-02-26 13:23
Thanks Volker, 

Best wishes for the revision and the talk! Pitty I did not register in time for [SCB](https://coursesandconferences.wellcomegenomecampus.org/our-events/single-cell-biology-2020/), would love to hear the talk

**Comment by jipeifeng** [comment] 2020-03-04 04:09
Also encounter the same issue and look forwarding the enhancement.

**Comment by Mevelo** [comment] 2020-03-09 22:07
> Yes, it is not yet possible, but should be doable (at least some Beta version) by next week.
> 
> Will also talk about this limitation in detail at [SCB](https://coursesandconferences.wellcomegenomecampus.org/our-events/single-cell-biology-2020/).

Hi @VolkerBergen , just wondering if this feature was now available by any chance?

**Comment by yaolutian** [comment] 2020-03-12 19:59
Thanks for this amazing tool, I saw #144 seemed finished, yet, I did not quite get how to set the root exactly. is there any examples?

**Comment by benemead** [comment] 2020-05-12 21:36
Hi @VolkerBergen - any updates this feature being available? Would be extremely useful.

Also - any guidance on why particular datasets may have genes which lack curvature? Is it technology-dependent, sequencing depth, other?

**Comment by VolkerBergen** [comment] 2020-05-14 13:31
Agree, will have to prioritize finishing up https://github.com/theislab/scvelo/pull/144. 
@stefanpeidli, you were already applying the root prior to some of your data. Is there anything we need to further adjust in the PR?

Possible lack of curvature usually is due to biological rather than technical reasons. There's a multitude of possible pitfalls (which will be disclosed in a separate paper). Most often, this is due to timescale mismatch (when developmental time is much longer than splicing dynamics, or vice versa).

**Comment by stefanpeidli** [comment] 2020-05-14 14:52
@VolkerBergen the root prior worked fine for me the way it's implemented in my fork (and the PR). We might want to reconsider the strategy of double-initializing though, as it tends to take a lot of time. Currently I use linear regression r<sup>2</sup> as criterion to decide wether a second fit is needed to resolve ambiguity, which is probably improvable.

**Comment by benemead** [comment] 2020-05-14 16:53
Thanks @VolkerBergen and @stefanpeidli!

@VolkerBergen - timescale mismatch makes a ton of sense for the dataset I'm working with (cells differentiating over ~1 week with a bunch of samplings). The streamlines 'make sense' but are definitely reversed vs. real-time expectation, and most of my top phase plots are 'flat'.

@stefanpeidli - I'll try your fork out and see how it looks!

**Comment by benemead** [comment] 2020-06-05 22:25
Hi @VolkerBergen & @stefanpeidli,

Wanted to check in on this - I did try running @stefanpeidli's fork, but I encountered a bug in preprocessing via "scv.pp.moments", which I don't have running on main branch.

Also potentially relevant here but my issue is very similar to #173 - also working with intestinal epithelium, and am seeing similar 'flips' as @ogilliam

**Comment by ccruizm** [comment] 2020-08-20 09:09
Good day!

I am also interested in knowing if there is now a way to set the 'root_cells'? I have also a similar issue like @zakiF where the endpoint is taken as the root and vice versa. It will be of great help if we can set up these parameters! thanks in advance

**Comment by oligomyeggo** [comment] 2020-09-23 22:21
Hello! Thank you for the great toolkit and informative tutorials! I am having similar issues/questions as above. I have a dataset where the velocity embedding graphs look great and as expected biologically. However, neither my `scv.tl.velocity_pseudotime` or `scv.tl.latent_time` are correct; the models are failing to identify any `root_cells`, and are not finding all the `end_points`. Is there a way to manually identify clusters as the starting/root and end points? That would be extremely helpful!

Related(ish), and this might be naive, but where are the individual cell id numbers stored? For instance, in this line of code: `x, y = scv.utils.get_cell_transitions(merge, basis='umap', starting_cell=897)`, how do I get the `int` denoting the cell I want to use for `starting_cell`? Is there a way to visualize these cell indexes on a UMAP?

Thank you for any help/advice!

**Comment by zhanglab2008** [comment] 2020-11-04 14:02
I wonder if the root_cells approach is available yet? If so, could you give an example how to use it? Many thanks!

**Comment by galozs** [comment] 2020-11-25 06:38
@oligomyeggo I think you can use the index of the cell from your `adata.obs` if it is a cell ID then your starting cell can be it. 
It worked for me.

**Comment by ccruizm** [comment] 2021-04-16 14:31
Good day!

I was wondering if there is a solution for these datasets where the velocity is inverted. Thanks !

**Comment by vim15** [comment] 2021-05-26 16:13
Has there been an update on this? 
I still can't find anywhere the solution of how to specify a cluster as root (if this is possible). 

Thanks.

**Comment by WeilerP** [comment] 2021-05-26 16:22
@ccruizm, @vim15 this is still not possible. In general, the problem of inverted velocities is usually caused by the data being intrinsically too noisy or phase portraits being linear. Specifying start/end cell types would only help in the latter case. See also #216 or #267.

**Comment by vim15** [comment] 2021-05-26 16:29
Thanks @WeilerP, 

I've looked at both of those threads you've mentioned, thank you. My phase portraits are quite almond shaped for a number of genes - it's just that I'm getting a velocity that makes no sense. 
Would you be able to give an illustrative example how one could go about setting a specific cluster (e.g '0') as a root? As they are stored here  : 

`ddata.obs['seurat_clusters']`

returns them : 
`Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']
`

**Comment by WeilerP** [comment] 2021-05-26 17:12
There is no quick fix for this. You can check #144 where adding a root prior was attempted. However, the codes base has evolved significantly since then and the PR has not been debugged.

If you find some "nice" phase portraits concerning the shape, you should also check if the temporal ordering is consistent with known biology. If not, the problem lies somewhere else entirely and specifying root priors does not help! In case of consistency, the problem may be that non-informative genes (e.g. due to noisy phase portraits) are dominating the directionality. You could try removing them and fitting the dynamics on only genes you find useful (based on visually seeing them).

**Comment by WeilerP** [comment] 2021-07-09 08:27
Closed in favor of #368.

**Closed by WeilerP** 2021-07-09 08:27 UTC
Labels: feature

**Comment by hyjforesight** [comment] 2021-11-30 17:32
Hello scVelo,
Could you please tell us how to set the root clusters for running scVelo? My issue is that the initial cluster calculated by scVelo internally is not consistent with the classical Mki67+ and Lgr5+ clusters, which are already known as the stem cell clusters.
Thanks!
Best,
YJ

**Comment by TdzBAS** [comment] 2023-11-27 12:41
@hyjforesight have you solved this?
