### ISSUE TITLE
Error plotting velocity graph

### ISSUE THREAD

**Issue by bapoorva** [theislab/scvelo#863] opened 2022-04-14 18:45 UTC
Hi,

I'm running scVelo and when I tried to plot the velocity graph, I'm getting this error-

```
 scv.pl.velocity_embedding_stream(adata, basis="umap", color="seurat_clusters")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/appl/python-3.8/lib/python3.8/site-packages/scvelo/plotting/velocity_embedding_stream.py", line 252, in velocity_embedding_stream
    ax = scatter(
  File "/appl/python-3.8/lib/python3.8/site-packages/scvelo/plotting/scatter.py", line 308, in scatter
    default_color_map(adata, color) if color_map is None else color_map
  File "/appl/python-3.8/lib/python3.8/site-packages/scvelo/plotting/utils.py", line 345, in default_color_map
    if isinstance(c, str) and c in adata.obs.keys() and not is_categorical(adata, c):
  File "/appl/python-3.8/lib/python3.8/site-packages/scvelo/plotting/utils.py", line 55, in is_categorical
    strings_to_categoricals(data)
  File "/appl/python-3.8/lib/python3.8/site-packages/scvelo/tools/utils.py", line 301, in strings_to_categoricals
    df_keys = [key for key in df.columns if is_valid_dtype(df[key])]
  File "/appl/python-3.8/lib/python3.8/site-packages/scvelo/tools/utils.py", line 301, in <listcomp>
    df_keys = [key for key in df.columns if is_valid_dtype(df[key])]
  File "/appl/python-3.8/lib/python3.8/site-packages/scvelo/tools/utils.py", line 297, in is_valid_dtype
    is_string_dtype(values) or is_integer_dtype(values) or is_bool_dtype(values)
  File "/appl/python-3.8/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 1322, in is_bool_dtype
    arr_or_dtype = arr_or_dtype.categories
  File "/appl/python-3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 5583, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'categories'
```

Not sure how to fix it. Also, how do i save plots command line?

Thanks

**Comment by WeilerP** [comment] 2022-04-14 18:57
Seems like a duplicate of #811.

**Closed by WeilerP** 2022-04-14 18:57 UTC
