### ISSUE TITLE
Directed PAGA raises a TypeError

### ISSUE THREAD

**Issue by Marius1311** [theislab/scvelo#213] opened 2020-06-08 14:41 UTC
Not sure whether this is a cellrank or scvelo issue. Maybe @michalk8 can help as well. 

I compute the directed PAGA passing cellrank root/final state annotations:
`scv.tl.paga(adata, groups='clusters', root_key='root_states_probs', end_key='final_states_probs')`
Using `scv.pl.paga(adata, basis='umap', color='clusters')`, I can plot it, that works fine. However, when I call `cr.pl.cluster_fates(adata, mode='paga_pie')`, I get the following exception:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-212-c5cfc7395251> in <module>
----> 1 cr.pl.cluster_fates(adata, mode='paga_pie')

~/Projects/cellrank/cellrank/plotting/_cluster_fates.py in cluster_fates(adata, cluster_key, clusters, lineages, mode, final, basis, show_cbar, ncols, sharey, save, legend_kwargs, figsize, dpi, **kwargs)
    491         if "paga" not in adata.uns:
    492             raise KeyError("Compute PAGA first as `scanpy.tl.paga()`.")
--> 493         fig = plot_paga_pie()
    494     elif mode == "violin":
    495         fig = plot_violin_no_cluster_key() if cluster_key is None else plot_violin()

~/Projects/cellrank/cellrank/plotting/_cluster_fates.py in plot_paga_pie()
    225             kwargs["color"] = cluster_key
    226 
--> 227         ax = scv.pl.paga(adata, **kwargs)
    228         ax.set_title(kwargs.get("title", cluster_key))
    229 

~/Projects/scvelo/scvelo/plotting/paga.py in paga(adata, basis, vkey, color, layer, title, threshold, layout, layout_kwds, init_pos, root, labels, single_component, dashed_edges, solid_edges, transitions, node_size_scale, node_size_power, edge_width_scale, min_edge_width, max_edge_width, arrowsize, random_state, pos, node_colors, normalize_to_color, cmap, cax, cb_kwds, add_pos, export_to_gexf, plot, use_raw, size, groups, components, figsize, dpi, show, save, ax, ncols, scatter_flag, **kwargs)
    246             ax = scatter(adata, basis=basis, x=x, y=y, vkey=vkey, layer=layer, color=paga_groups, size=size,
    247                          title=title, ax=ax, save=None, zorder=0, show=False, **kwargs)
--> 248         _paga(adata, ax=ax, show=False, text_kwds={'zorder': 1000, 'alpha': legend_loc == 'on data'}, **paga_kwargs)
    249 
    250         savefig_or_show(dpi=dpi, save=save, show=show)

~/Projects/scvelo/scvelo/plotting/paga.py in _paga(adata, threshold, color, layout, layout_kwds, init_pos, root, labels, single_component, solid_edges, dashed_edges, transitions, fontsize, fontweight, fontoutline, text_kwds, node_size_scale, node_size_power, edge_width_scale, min_edge_width, max_edge_width, arrowsize, title, random_state, pos, normalize_to_color, cmap, cax, colorbar, cb_kwds, frameon, add_pos, export_to_gexf, use_raw, colors, groups, plot, show, save, ax, **scatter_kwargs)
    412                               cmap=cmap, colorbar=colorbars[icolor], cb_kwds=cb_kwds, use_raw=use_raw,
    413                               title=title[icolor], export_to_gexf=export_to_gexf, single_component=single_component,
--> 414                               arrowsize=arrowsize, pos=pos)
    415             if colorbars[icolor]:
    416                 if cax is None:

~/Projects/scvelo/scvelo/plotting/paga.py in _paga_graph(adata, ax, solid_edges, dashed_edges, adjacency_solid, adjacency_dashed, transitions, threshold, root, colors, labels, fontsize, fontweight, fontoutline, text_kwds, node_size_scale, node_size_power, edge_width_scale, normalize_to_color, title, pos, cmap, frameon, min_edge_width, max_edge_width, export_to_gexf, colorbar, use_raw, cb_kwds, single_component, arrowsize)
    541         colors = asso_colors
    542 
--> 543     if len(colors) < len(node_labels):
    544         raise ValueError('`color` list need to be at least as long as `groups`/`node_labels` list.')
    545 

TypeError: object of type 'int' has no len()
```

#### Versions:
scvelo==0.2.2.dev10+ga7b7ec9  scanpy==1.5.1  anndata==0.7.3  loompy==3.0.6  numpy==1.18.3  scipy==1.4.1  matplotlib==3.2.1  sklearn==0.22  pandas==1.0.3

**Comment by michalk8** [comment] 2020-06-08 15:11
This seems more like `CellRank` issue, but I was unable to reproduce it on the pancreas data. For reference, here's what's being passed in `kwargs` (`node_colors` a dict):
```python
        kwargs["ax"] = ax
        kwargs["show"] = False
        kwargs["colorbar"] = False  # has to be disabled
        kwargs["show"] = False

        kwargs["node_colors"] = colors
        kwargs.pop("save", None)  # we will handle saving

        kwargs["transitions"] = kwargs.get("transitions", None)
        if "legend_loc" in kwargs:
            orig_ll = kwargs["legend_loc"]
            if orig_ll != "on data":
                kwargs["legend_loc"] = "none"  # we will handle legend
        else:
            orig_ll = None
            kwargs["legend_loc"] = "on data"

        if basis is not None:
            kwargs["basis"] = basis
            kwargs["scatter_flag"] = True
            kwargs["color"] = cluster_key
```

**Comment by VolkerBergen** [comment] 2020-06-11 05:13
Since not related to scvelo, I'd close this and suggest to move the issue to cellrank.

**Closed by VolkerBergen** 2020-06-11 05:13 UTC
Labels: bug
