### ISSUE TITLE
error when running scv.tl.velocity_graph(adata)

### ISSUE THREAD

**Issue by mimisikai** [theislab/scvelo#954] opened 2022-11-04 19:12 UTC
Follow this tutorial https://smorabit.github.io/tutorials/8_velocyto/ and apply to my data. 
Every steps run smoothly till scv.tl.velocity_graph(adata), see error below 

```python
import scvelo as scv
import scanpy as sc
import cellrank as cr
import numpy as np
import pandas as pd
import anndata as ad
import os

os.chdir("/Users/jhou2/Documents/HSV RNAseq/scRNAseq/Velocity")

scv.settings.verbosity = 3
scv.settings.set_figure_params('scvelo', facecolor='white', dpi=100, frameon=False)
cr.settings.verbosity = 2
adata = sc.read_h5ad('HSV_combine.h5ad')

# load loom files for spliced/unspliced matrices for each sample:
ldata1 = scv.read('/Users/jhou2/Documents/HSV RNAseq/loom files/AW15979_022222_V1_Lesion_P.loom', cache=True)
ldata2 = scv.read('/Users/jhou2/Documents/HSV RNAseq/loom files/JB15490_102721_2_GS_Control.loom', cache=True)
ldata3 = scv.read('/Users/jhou2/Documents/HSV RNAseq/loom files/JB15490_113021_2_GS_Lesion.loom', cache=True)

# rename barcodes in order to merge:
# ldata1 is AW lesion, suffix is 8
barcodes = [bc.split(':')[1] for bc in ldata1.obs.index.tolist()]
barcodes = [bc[0:len(bc)-1] + '_8' for bc in barcodes]
ldata1.obs.index = barcodes

# ldata2 is JB entry, suffix is 9
barcodes = [bc.split(':')[1] for bc in ldata2.obs.index.tolist()]
barcodes = [bc[0:len(bc)-1] + '_9' for bc in barcodes]
ldata2.obs.index = barcodes

# ldata3 is JB lesion, suffix is 6
barcodes = [bc.split(':')[1] for bc in ldata3.obs.index.tolist()]
barcodes = [bc[0:len(bc)-1] + '_6' for bc in barcodes]
ldata3.obs.index = barcodes

# make variable names unique
ldata1.var_names_make_unique()
ldata2.var_names_make_unique()
ldata3.var_names_make_unique()
# concatenate the three loom
ldata = ldata1.concatenate([ldata2, ldata3])
# merge matrices into the original adata object
adata = scv.utils.merge(adata, ldata)
# plot umap to check
sc.pl.umap(adata, color='CellType', frameon=False, legend_loc='on data', title='', save='_celltypes.pdf')

scv.pl.proportions(adata, groupby='CellType', save='Proportion_CellTypes.pdf')

# pre-process
scv.pp.filter_and_normalize(adata)
scv.pp.moments(adata)

# compute velocity
scv.tl.velocity(adata, mode='stochastic')
scv.tl.velocity_graph(adata)
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/Step1 Load data.py", line 56, in <module>
    scv.tl.velocity_graph(adata)
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/scvelo/tools/velocity_graph.py", line 363, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/scvelo/tools/velocity_graph.py", line 175, in compute_cosines
    res = parallelize(
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/scvelo/core/_parallelize.py", line 122, in wrapper
    queue = Manager().Queue()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/Step1 Load data.py", line 56, in <module>
    scv.tl.velocity_graph(adata)
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/scvelo/tools/velocity_graph.py", line 363, in velocity_graph
    vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/scvelo/tools/velocity_graph.py", line 175, in compute_cosines
    res = parallelize(
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/scvelo/core/_parallelize.py", line 122, in wrapper
    queue = Manager().Queue()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```
</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```
</details>

**Comment by mimisikai** [comment] 2022-11-04 21:16
Some updates:
`scv.pl.hist(adata.var['velocity_r2'])`
![Figure_1](https://user-images.githubusercontent.com/4881411/200076046-34d62614-bfbf-4488-81b6-b4e39477ac65.png)

`print(adata.var['velocity_genes'])`
MIR1302-2HG    False
FAM138A        False
OR4F5          False
AL627309.1     False
AL627309.3     False
               ...  
AC010086.3     False
AC024236.1     False
PRYP3          False
AC213203.2     False
AC004556.3     False
Name: velocity_genes, Length: 36475, dtype: bool

**Comment by mimisikai** [comment] 2022-11-04 21:21
`print(adata.var['velocity_genes'].sum())`
1961

`print(adata.layers['velocity'])`
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

**Comment by mimisikai** [comment] 2022-11-04 21:29
AnnData object with n_obs × n_vars = 15547 × 36475
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'percent.ribo', 'Subject', 'Status', 'integrated_snn_res.0.5', 'seurat_clusters', 'CellType', 'barcode', 'UMAP_1', 'UMAP_2', 'sample_batch', 'batch', 'initial_size_spliced', 'initial_size_unspliced', 'initial_size'
    var: 'Accession', 'Chromosome', 'End', 'Start', 'Strand'
    uns: 'CellType_colors', 'Subject_colors'
    obsm: 'X_pca', 'X_umap'
    layers: 'ambiguous', 'matrix', 'spliced', 'unspliced'

**Comment by mimisikai** [comment] 2022-11-04 21:37
I've tried on scv.datasets.pancreas() data, it returns a similar error but one more error is 
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.

I assume there is a basic problem happening somewhere not specific on my dataset.

**Comment by WeilerP** [comment] 2022-11-07 08:03
@mimisikai, seems like a duplicate of #746. I'm closing this for now.
Regarding the error on the pancreas dataset: This is caused by logging the used libraries and will be fixed in a future version.

**Closed by WeilerP** 2022-11-07 08:03 UTC
Labels: bug, duplicate
