### ISSUE TITLE
Cannot find gene feature for scatter plot after running dynamical model 

### ISSUE THREAD

**Issue by Lobbii** [theislab/scvelo#511] opened 2021-06-26 19:47 UTC
I have performed scv.tl.recover_dynamics, and I found the fitting information in anndata.var. But I cannot generate scatter plot showing transactional switches with  scv.pl.scatter(WT_WT, x='latent_time', y='IL1RN', frameon=False)  

I can find fitted parameters for splicing dynamics in adata.var. and IL1RN is a dynamical genes shown in heatmap of dynamics genes vs inferred latent time. Besides, I can generate the scatter plot showing learned dynamics for IL1RN. 

I have run the script shown below:
`scv.pp.filter_and_normalize(WT_WT, min_shared_counts=20, n_top_genes=2000)`
`scv.pp.moments(WT_WT, n_pcs=30, n_neighbors=30)`
`scv.tl.recover_dynamics(WT_WT)`
`scv.tl.velocity(WT_WT, mode='dynamical')`
`scv.tl.velocity_graph(WT_WT)`
`scv.tl.latent_time(WT_WT)`
`scv.pl.scatter(WT_WT, color='latent_time', color_map='gnuplot', size=80)`
`top_genes = WT_WT.var['fit_likelihood'].sort_values(ascending=False).index[:300]`
`scv.pl.heatmap(WT_WT, var_names=top_genes, sortby='latent_time', col_color='SCT_snn_res.0.2', n_convolve=100)`

AnnData object with n_obs × n_vars = 3129 × 2000
obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'Cells', 'Update_Cells', 'nCount_spliced', 'nFeature_spliced', 'nCount_unspliced', 'nFeature_unspliced', 'nCount_ambiguous', 'nFeature_ambiguous', 'initial_size_spliced', 'initial_size_unspliced', 'initial_size', 'n_counts', 'velocity_self_transition', 'root_cells', 'end_points', 'velocity_pseudotime', 'latent_time'
var: 'features', 'SCT_features', 'ambiguous_features', 'spliced_features', 'unspliced_features', 'means', 'dispersions', 'dispersions_norm', 'highly_variable', 'fit_r2', 'fit_alpha', 'fit_beta', 'fit_gamma', 'fit_t_', 'fit_scaling', 'fit_std_u', 'fit_std_s', 'fit_likelihood', 'fit_u0', 'fit_s0', 'fit_pval_steady', 'fit_steady_u', 'fit_steady_s', 'fit_variance', 'fit_alignment_scaling', 'velocity_genes'
uns: 'pca', 'neighbors', 'recover_dynamics', 'velocity_params', 'velocity_graph', 'velocity_graph_neg'
obsm: 'X_umap', 'X_pca', 'velocity_umap'
varm: 'PCs', 'loss'
layers: 'SCT', 'ambiguous', 'spliced', 'unspliced', 'Ms', 'Mu', 'fit_t', 'fit_tau', 'fit_tau_', 'velocity', 'velocity_u'
obsp: 'distances', 'connectivities'

**Comment by WeilerP** [comment] 2021-06-27 18:15
@Lobbii would you please provide the package versions you are using as well as the line of code causing the problem and the corresponding stack trace?

**Comment by WeilerP** [comment] 2021-06-27 19:26
Duplicate of #508.

**Closed by WeilerP** 2021-06-27 19:26 UTC
