### ISSUE TITLE
PAGA gives opposite direction too embedding stream for some clusters

### ISSUE THREAD

**Issue by Leena-Abdullah** [theislab/scvelo#1014] opened 2023-03-06 00:10 UTC
<img width="519" alt="Screen Shot 2023-03-05 at 7 05 27 PM" src="https://user-images.githubusercontent.com/95719967/222993946-9ccae624-b927-4e44-a9d5-967c02b51c00.png">

Hello, 

I am using scvelo and I noticed that my PAGA plot is not in agreement with the embedding grid or stream plots. The embedding stream and grid plots are in complete agreement only for some clusters PAGA is showing the arrows in the wrong direction. Any help would be appreciated. I did pre-process my data using scv.pp.filter_and_normalize(adata)

Thank you!

**Comment by WeilerP** [comment] 2023-03-16 10:03
Closed as duplicate of #313.

**Closed by WeilerP** 2023-03-16 10:03 UTC
Labels: duplicate
