### ISSUE TITLE
Proportions don't add up to 100%

### ISSUE THREAD

**Issue by LacquerHed** [theislab/scvelo#1100] opened 2023-07-19 21:49 UTC
When I run the following line of code:

`scv.pl.proportions(adata, groupby='celltype_full')`

I don't get the cluster spliced/unspliced proportions adding up to 100% as the venn does, wondering why this may be?

![Screen Shot 2023-07-19 at 5 45 36 PM](https://github.com/theislab/scvelo/assets/81645917/1e5778ea-e598-465e-8b19-925c325d96ca)

Thanks!

**Comment by WeilerP** [comment] 2023-07-23 16:49
@LacquerHed, I suspect the issue is a duplicate of #733. Closing the issue for now. Please use the provided issue templates and reproducible code/explanations.

**Closed by WeilerP** 2023-07-23 16:49 UTC
Labels: bug
