### ISSUE TITLE
Unbound local error when running scv.utils.merge

### ISSUE THREAD

**Issue by erikmcintire** [theislab/scvelo#1075] opened 2023-06-05 15:29 UTC
I've run scvelo successfully in the past, but the last few months have been running into an issue when trying to merge the spliced/unspliced counts with scv.utils.merge. Specifically, I get 'Unbound local error.' I've tried several workarounds, such as downgrading to earlier versions of scvelo, running it locally instead of on our HPC, and recently tried to run it in a singularity container, but I always get the same error (below). I'm running it on the same files that I've had success with in the past, and am stuck. Any advice or guidance would be much appreciated, please let me know if I can provide any additional information.

![Screenshot 2023-06-05 at 10-20-34 Untitled2 - Jupyter Notebook](https://github.com/theislab/scvelo/assets/54911419/3e62331e-97f4-4b3a-8b15-9d0fc94bef12)

**Comment by WeilerP** [comment] 2023-06-05 15:33
Duplicate of several other issues. Please search existing (already closed and resolved) issues before opening a new one.

**Closed by WeilerP** 2023-06-05 15:33 UTC
Labels: duplicate
