### ISSUE TITLE
nan values in 'fit_t' 'fit_tau' and 'fit_tau_' produced after running the scv.tl.recover_dynamics function

### ISSUE THREAD

**Issue by thuthao** [theislab/scvelo#872] opened 2022-04-29 17:24 UTC
Hi, 
I got odd directions of velocity vectors and tried to trace back where it went wrong. The scv.tl.recover_dynamics did not give out any specific errors yet the fit parameters were all 'nan'.

> recovering dynamics (using 24/24 cores)
>     finished (0:00:46) --> added 
>     'fit_pars', fitted parameters for splicing dynamics (adata.var)

Notably, the time required for this step was too fast also (46 seconds) so there must be something wrong with my data. How should I check for the source of this problem?
Thanks,
Thao

**Comment by WeilerP** [comment] 2022-04-29 19:54
@thuthao seems like a duplicate of a collection of issues. Please have a look at e.g. #774, #216 or #462.

**Closed by WeilerP** 2022-04-29 19:54 UTC
