### ISSUE TITLE
Too many dependencies are being installed

### ISSUE THREAD

**Issue by LouisFaure** [theislab/scvelo#1214] opened 2024-03-05 18:36 UTC
Here is a suggestion:

scvelo has always been a lightweight tool that is fast to install and quick to use. However, since the introduction of VeloVI, installing scvelo lead to the installation of many dependencies (most requested by torch->scvi-tools). In systems without GPUs, it feels rather unnecessary to see cuda related packages being installed. Moreover, not everyone seeks to use VeloVI. Would it be possible to make the installation of VeloVI and related dependencies optional?

Another way could be to keep the current installation as default, but propose another more lightweight one under `scvelo[notorch]` for example

**Comment by WeilerP** [comment] 2024-03-05 18:52
Duplicate of #1189 and #1185. Please check open and resolved issues and PRs before opening new ones.
The feature is already available on `main`; the plan is to have a release soon.

**Closed by WeilerP** 2024-03-05 18:52 UTC
Labels: enhancement

**Comment by LouisFaure** [comment] 2024-03-05 18:53
apologies, I tried some search in resolved issues but I was not good enough apparently
