### ISSUE TITLE
Dynamic model fails to resolve velocity directions at cluster boundaries

### ISSUE THREAD

**Issue by Leena-Abdullah** [theislab/scvelo#1032] opened 2023-03-29 19:07 UTC
Hello,

I have been trying to troubleshoot the dynamic model for sometime however the arrows sort of converge into each other at the boundary of different clusters. I don't have this directionality issue with the stochastic model. Here I am sharing my top_liklihood genes (first 20) and the velocity stream with the dynamical and steady state model. 

Also, for clarification purposes are the velocity genes used by the 3 model dynamic, stochastic and steadystate the same?
What does it mean in terms of how the model is covering that that the arrows of the velocity stream arrows are moving into each other at the cluster boundaries?

Would really appreciate your help with this.

phase diagrams for the top 20 likelihood genes usign the dynamical model
 
<img width="174"
<img width="1147" alt="top 20 liklihood genes phase diagrams" src="https://user-images.githubusercontent.com/95719967/228642773-a4382995-5191-4f47-b906-dc198984e620.png">

Dynamic model velocity stream

<img width="174" alt="Dynamic model velocity stream" src="https://user-images.githubusercontent.com/95719967/228642764-0814a0e3-e6c0-4838-8d1a-e94ed020ac01.png">
 alt="Steady_state model velocity stream" src="https://user-images.githubusercontent.com/95719967/228642745-76c33793-bc5d-4474-b732-b23d0cafe906.png">

Steady_state model velocity stream

<img width="174" alt="Steady_state model velocity stream" src="https://user-images.githubusercontent.com/95719967/228643146-23b79500-8566-4146-a4f7-537f02338015.png">

**Comment by WeilerP** [comment] 2023-03-29 19:32
Not a code related issue or bug so I am closing this. It's also a duplicate of multiple in-depth discussions/issues. Please have a look there.

**Closed by WeilerP** 2023-03-29 19:32 UTC

**Comment by Leena-Abdullah** [comment] 2023-03-29 19:59
I have seen other issues like this however, in my head the phase portrait of some of these genes like Zeb2 and Pycard look dynamic but the dynamical model is still failing. So, I am unclear on whether the model is failing because my top-liklihood genes aren't dynamic enough?
