### ISSUE TITLE
Link to dataset is wrong

### ISSUE THREAD

**Issue by sandrav-CGEN** [theislab/scvelo#925] opened 2022-09-20 13:15 UTC
A minor bug, when I tried to access the publication for the bone marrow dataset via the provided link it led me to the publication of the pancreas dataset.
![image](https://user-images.githubusercontent.com/104442627/191267477-b9c8c166-2c97-4339-b995-33693f0a6fa1.png)

```python
# paste your code here, if applicable
```

<details>

<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```
</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```
</details>

**Comment by WeilerP** [comment] 2022-09-20 13:20
Closing this since it's a duplicate of #747.

**Closed by WeilerP** 2022-09-20 13:20 UTC
Labels: bug
