### ISSUE TITLE
'scvelo' has no attribute 'pp'

### ISSUE THREAD

**Issue by ryrl9703** [theislab/scvelo#948] opened 2022-10-26 08:15 UTC
...
Hello, it works well when I ran the scvelo on pycharm. However, when tha save the script and ran on linux command line, just like: python scvelo.py, it always report that:

                       'scvelo' has no attribute 'pp'

```python
# paste your code here, if applicable
```

Traceback (most recent call last):
  File "/public/workspace/ryrl/idea/scRNA/dhsu/dhsu/scvelo/scvelo.py", line 112, in <module>
    scv.pp.filter_and_normalize(adata)
AttributeError: module 'scvelo' has no attribute 'pp'. Did you mean: 'np'?

<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```
</details>

0.2.4

```pytb
# paste the ouput of scv.logging.print_versions() here
```
</details>

**Comment by WeilerP** [comment] 2022-10-26 08:35
@ryrl9703, as asked for in the template: Please paste a code snippet (in your case the content of `scvelo.py`, for example) I can simply copy and paste to ideally reproduce your error. I never encountered this problem before and just ran a script as you describe without issues. Seems like the issue is on your end?

**Comment by WeilerP** [comment] 2022-10-28 14:01
@ryrl9703 closing this for now since it's an issue on your end. Let me know it you there is an update (e.g. specific commands and script I can run to reproduce your error).

**Closed by WeilerP** 2022-10-28 14:01 UTC
Labels: bug
