### ISSUE TITLE
utils.merge function raises an UnboundLocalError about clean_obs_names

### ISSUE THREAD

**Issue by monica-nicolau** [theislab/scvelo#1057] opened 2023-05-11 22:34 UTC
Hi everyone!

While I was trying to merge the .h5ad adata with .loom ldata with the scv.utils.merge() function, I got the following error:
```
 Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/apps/Python-3.8.1/lib/python3.8/site-packages/scvelo/core/_anndata.py", line 526, in merge
    clean_obs_names(adata, id_length=id_length)
UnboundLocalError: local variable 'id_length' referenced before assignment
```
By looking at the merge() code (lines 38-43) it seems that the id_length variable is passed as argument of clean_obs_names() even if it is not in the kwawrgs. 
I am just a beginner in Python, so apologies if this is dumb observation, but shouldn't **lines 41-42** be indented inside the inner if (so as line 40)?
Or shouldn't the id_length variable be assigned a default value in case it is not present in the kwargs?

```
38 if len(common_obs) == 0:
39         if "id_length" in kwargs:
40             id_length = kwargs.get("id_length")
41         clean_obs_names(adata, id_length=id_length)
42         clean_obs_names(ldata, id_length=id_length)
43         common_obs = adata.obs_names.intersection(ldata.obs_names)
```

By the way, I managed to elude the error by passing the id_length in the arguments of the merge() function as following:

```
adata = scv.utils.merge(adata,ldata, id_length=12)
```
since 12 is the default value of id_length set by clean_obs_names()

I would really appreciate your feedback on this issue :)

```pytb
scv.logging.print_versions()
scvelo==0.2.5  scanpy==1.9.3  anndata==0.9.1  loompy==3.0.7  numpy==1.21.1  scipy==1.10.1  matplotlib==3.7.1  sklearn==1.2.1  pandas==1.3.1
```

**Comment by WeilerP** [comment] 2023-05-12 01:12
Duplicate of #983. Please check existing issues before opening a new one.

**Closed by WeilerP** 2023-05-12 01:12 UTC
Labels: bug
