### ISSUE TITLE
ValueError: non-broadcastable output operand with shape (5170,) doesn't match the broadcast shape (1,5170)

### ISSUE THREAD

**Issue by fbrundu** [theislab/scvelo#98] opened 2019-10-15 15:26 UTC
I get the following error when trying to run `rank_velocity_genes()`:

```python
> scv.tl.rank_velocity_genes(fdata, groupby=key)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Dropbox/work/colu17/proj/2018_hsc/code/v03/06.pseudotime.velocity.py in 
----> 1 scv.tl.rank_velocity_genes(fdata, groupby=key)

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/scvelo/tools/rank_velocity_genes.py in rank_velocity_genes(data, vkey, n_genes, groupby, match_with, resolution, min_counts, min_r2, min_dispersion, min_likelihood, copy)
    176         n_counts = n_counts.A1 if issparse(adata.layers['unspliced']) else n_counts
    177         min_counts = min(50, np.percentile(n_counts, 50)) if min_counts is None else min_counts
--> 178         tmp_filter &= (n_counts > min_counts)
    179 
    180     if vkey + '_r2' in adata.var.keys():

ValueError: non-broadcastable output operand with shape (5170,) doesn't match the broadcast shape (1,5170)
```

where `fdata` is the AnnData with velocity results and `key` is the name of the column in obs with the leiden clustering labels.

I think [this](https://stackoverflow.com/a/47493938/41977) may work as a solution, but I'm unsure if I'm executing scvelo correctly.

**Comment by stefanpeidli** [comment] 2019-10-22 16:00
I cannot reproduce the error when using louvain instead of leiden clustering
`scv.tl.louvain(adata)
scv.tl.rank_velocity_genes(adata, groupby='louvain')`

How does your `fdata.obs['leiden']` look like?

**Comment by VolkerBergen** [comment] 2019-10-22 16:04
Merged your PR. Thanks!

**Closed** 2019-10-22 16:04 UTC
