### ISSUE TITLE
AttributeError after "scv.pp.moments" command

### ISSUE THREAD

**Issue by panapapa14** [theislab/scvelo#1269] opened 2024-09-19 11:47 UTC
Hi there. I have been trying to run scvelo for two weeks now, figuring out workarounds for several issues like memory ones and so on.
Having downsampled my dataset, reduced certain parameters, kept genes of certain expression levels and done PCA, I was hopinng to find a way to make it work, but nope.
 Now I am dealing with the following error: 

>> scv.pp.moments(adata_filtered_spliced, n_pcs=20, n_neighbors=5)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/splab/miniconda3/lib/python3.12/site-packages/scvelo/preprocessing/moments.py", line 63, in moments
     neighbors(
   File "/home/splab/miniconda3/lib/python3.12/site-packages/scvelo/preprocessing/neighbors.py", line 223, in neighbors
     n_duplicate_cells = len(get_duplicate_cells(adata))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/splab/miniconda3/lib/python3.12/site-packages/scvelo/preprocessing/neighbors.py", line 555, in get_duplicate_cells
     X_new = np.array(X[idx_dup].A if issparse(X) else X[idx_dup])
                      ^^^^^^^^^^^^
AttributeError: 'csr_matrix' object has no attribute 'A'
 ...
Everything is updated and I even tried (multiple times) to proceed to manual changes of the involved .py files (according to the error).

Any help would be extremely valuable! Thank you for your time.

```python
# paste your code here, if applicable
```

<details>

<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```

</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```

</details>

**Comment by WeilerP** [comment] 2024-09-24 05:01
Duplicate of #1260; see #1263.

**Closed by WeilerP** 2024-09-24 05:01 UTC
Labels: bug
