### ISSUE TITLE
velocity_graph

### ISSUE THREAD

**Issue by mimisikai** [theislab/scvelo#997] opened 2023-02-02 20:22 UTC
cell connection networking separate from cell dots.   

```python
# paste your code here, if applicable
```

<details>

<summary> Error output </summary>

![Screen Shot 2023-02-02 at 12 23 46 PM](https://user-images.githubusercontent.com/4881411/216441575-4e007799-88f7-4e85-9d3e-11f1142a797d.png)

</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```

</details>

**Comment by WeilerP** [comment] 2023-02-02 20:27
Closing this since no code to reproduce issue provided and seems like a duplicate of #996. @mimisikai please search among the issues first, provide a meaningful description and all information asked for.

**Closed by WeilerP** 2023-02-02 20:27 UTC
Labels: bug
