### ISSUE TITLE
Problems with scv.utils.merge function

### ISSUE THREAD

**Issue by VivianeSchulz** [theislab/scvelo#1015] opened 2023-03-10 13:42 UTC
I am trying to run a velocity analysis, however whenever I try to merge my data with my loom files I get an error (code and error attached).
I've tried it on a file for which this command previously worked (but now it no longer does) as well as trying to merge two loom files, which also gives me this error. So I believe it's to do with a package version rather than the files themselves, but I cannot seem to figure out which packages are responsible and which versions I would need instead.
Any help would be greatly appreciated!

My code:
adata_vel = scv.utils.merge(adata, adatal)

This is my error:
<img width="844" alt="Screenshot 2023-03-09 at 11 43 11" src="https://user-images.githubusercontent.com/85882727/224330978-d3a1d72c-29c5-4111-b446-385712bfb36d.png">

Versions:
IPython 8.0.1
jupyter_client 6.1.12
jupyter_core 4.7.1
jupyterlab 3.0.14
notebook 6.3.0

Python 3.8.8 (default, Apr 13 2021, 12:59:45) [Clang 10.0.0 ]
macOS-10.15.7-x86_64-i386-64bit

scvelo==0.2.5  scanpy==1.8.1  anndata==0.8.0  loompy==3.0.6  numpy==1.22.0  scipy==1.6.2  matplotlib==3.3.4  sklearn==0.24.1  pandas==1.5.3

**Comment by WeilerP** [comment] 2023-03-13 17:53
Duplicate of https://github.com/theislab/scvelo/issues/983. Please search open issues first, do not open a duplicate one, and use the issue template for bugs.

**Closed by WeilerP** 2023-03-13 17:53 UTC
Labels: bug, duplicate
