### ISSUE TITLE
velocity stream and PAGA arrows direction are opposite 

### ISSUE THREAD

**Issue by galozs** [theislab/scvelo#313] opened 2020-11-24 11:38 UTC
Hi
Thanks for this great tool!
I have plotted the velocities stream on the umap and calculated PAGA connections and the direction of the arrows in the PAGA graph do not match the vlocities

![Picture1](https://user-images.githubusercontent.com/25480917/100088280-8cd98f00-2e58-11eb-96f0-3ca1d6e2d4b8.png)

I'm specifically bothered by clusters 2 and 6 directionality which is opposite. 
5 to 8 and 1 to 0 are not opposite but not perfectly match as well. 

Regarding cluster 9 - I suspect it is highly affected by cell cycle. these cells express genes like Mki67 and others. 
Is it possible that this is the reason for all the connections in PAGA graph coming out of cluster9 ?
This is the umap with cell cycle markers
![Capture](https://user-images.githubusercontent.com/25480917/100089376-3c633100-2e5a-11eb-993d-efbe2125b66d.JPG)

`scv.tl.velocity` mode was set to "stochastic"
I also ran these two lines before the PAGA as it says in the tutorial
`adata.uns['neighbors']['distances'] = adata.obsp['distances']
adata.uns['neighbors']['connectivities'] = adata.obsp['connectivities']`

I saw some other issues with similar questions however I couldn't find any suggestion that solved it or helped me understand what happen in my data.
Thanks!

**Comment by shexiaolu** [comment] 2021-05-24 07:17
+1. I have the same issue!!! And i don't know why?

**Comment by WeilerP** [comment] 2021-05-30 08:10
Closed as duplicate of #456.

**Closed by WeilerP** 2021-05-30 08:10 UTC
Labels: duplicate
