### ISSUE TITLE
scv.pp.filter_and_normalize warned "Did not normalise X" even though the input data were not normalised, resulting in unusually high unspliced proportion 

### ISSUE THREAD

**Issue by denvercal1234GitHub** [theislab/scvelo#1052] opened 2023-05-05 12:38 UTC
Hi there, 

I merged Seurat object (with computed UMAP and clustering) and unprocessed (raw) loom objects in Python following the workflow below. 

I did not normalise or manipulate the loom data  (spliced, unspliced, ambiguous) in any way (except the cell barcodes to match so I can merge with the Seurat object converted to anndata).  `scv.pp.filter_and_normalize` was ran **after** running the proportion check `scv.pl.proportions`! However,` scv.pp.filter_and_normalize` still gave the warning of "normalised count data" as below. 

Is this because the Seurat count data were normalised, so when I merged the loom object with the Seurat object, even though the loom object is not normalised, `scv.pp.filter_and_normalize` still think it is normalised?

Thank you for your help!

**My workflow (https://github.com/theislab/scvelo/discussions/1047)**
1. Read in each of the loom objects with `scv.read()` as adata
2. Rename the `.obs.index` of these loom adata to match the cell barcode naming of my Seurat object 
3. Do `.var_names_make_unique()` to the loom objects 
4. Do `.concatenate` to concatenate all the loom object adata 
5. Read in my Seurat object (that was fully processed and clustered in R, and converted into h5d file - below) with `sc.read_h5ad` 
6. Check the `.obs_names` for the concatenated loom match with the `.obs_names` of the Seurat object
7. Do `scv.utils.merge` to merge the Seurat object and the concatenated loom
8. Perform `scv.pp.filter_and_normalize(min_shared_counts=30, n_top_genes=3000, retain_genes = clusteringFineTune_genes_list)` 
9. Perform `scv.pp.moments(n_pcs=30, n_neighbors=30)`
10. Perform `scv.tl.recover_dynamics` and `scv.tl.velocity( mode='dynamical')` with default parameters as in the tutorial 

**This is my Seurat object:**
<img width="646" alt="Screenshot 2023-05-03 at 21 01 43" src="https://user-images.githubusercontent.com/62179082/236034921-d9f976eb-c9b0-4571-962f-3dc898056726.png">

**This is my loom object:**
<img width="455" alt="Screenshot 2023-05-04 at 09 42 35" src="https://user-images.githubusercontent.com/62179082/236154262-054a9715-28af-4925-9496-2b5876424cb7.png">

**This is my merged object of the Seurat and concatenated loom:**
<img width="554" alt="Screenshot 2023-05-03 at 21 03 48" src="https://user-images.githubusercontent.com/62179082/236035504-ca3c90c0-7b94-46e5-823a-38ab2c61347d.png">

<img width="776" alt="Screenshot 2023-05-04 at 09 51 06" src="https://user-images.githubusercontent.com/62179082/236156280-230443c4-1dcb-433e-8f54-f80fd434b8b8.png">

This bug could explain the unusually high unspliced % as reported by @chrismahony https://github.com/theislab/scvelo/discussions/845 and https://github.com/theislab/scvelo/discussions/933

```
scvelo==0.2.5  scanpy==1.9.3  anndata==0.7.6  loompy==3.0.7  numpy==1.23.5  scipy==1.10.1  matplotlib==3.7.1  sklearn==1.2.2  pandas==1.5.3  
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI no longer supports 'pip search' (or XML-RPC search). Please use https://pypi.org/search (via a browser) instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.
```

**Comment by WeilerP** [comment] 2023-05-05 13:01
@denvercal1234GitHub please provide the actual code, not prose. Are you running `scv.utils.merge(adata_loom, adata_seurat)` or `scv.utils.merge(adata_seurat, adata_loom)`? Based on the behavior, I suspect the latter.
1. You should call `scv.utils.merge(adata_loom, adata_seurat)`?
2. If you already do, can you please check that `adata_loom.X` really contains raw counts? Did you process it with velocyto or another aligner? Other alignment methods may give you pseudo counts which throws off scvelo.
3. Can you please check that the merged object looks as you expect, _i.e._, is `adata_loom` but subsetted to the genes present in both the Seurat and LOOM adata?

**Comment by denvercal1234GitHub** [comment] 2023-05-05 16:18
Hi @WeilerP -- Thank you so much for pointing that out! 

**1. Below is my workflow.** `count302_chrMTGTF_concat_adata` is my concatenated loom object, and `IndividualDatasetMERGED_adata` is my Seurat clustered obj converted from Seurat to h5ad. I now specified in `scv.utils.merge(adata = count302_chrMTGTF_concat_adata, ldata =IndividualDatasetMERGED_adata)`


```
count302_R1_chrMTGTF_adata = scv.read( "..../loomForRNAVelocity/count_Ton246_CD8R5pos_R1_chrMTGTF.loom")
count302_R2_chrMTGTF_adata = scv.read( "..../loomForRNAVelocity/count_Ton246_CD8R5pos_R2_chrMTGTF.loom")

count302_R1_chrMTGTF_adata.var_names_make_unique()
count302_R2_chrMTGTF_adata.var_names_make_unique()

count302_chrMTGTF_concat_adata = count302_R1_chrMTGTF_adata.concatenate([count302_R2_chrMTGTF_adata])

#### Read in my Seurat object with UMAP and clustering done
IndividualDatasetMERGED_adata = sc.read_h5ad("........../viaSeuratDisk/IndividualDatasetMERGED_ann.h5ad")

#### Merge loom and Seurat object 
loomGEX_adata = scv.utils.merge(adata = count302_chrMTGTF_concat_adata, ldata =IndividualDatasetMERGED_adata)

```

**2. I used `velocyto run10x`.** I show the rows of concatenated loom object below. Do you know how to better check whether the values were raw or normalised because they are most just 0?

```
velocyto run10x -m ....../Velocyto/mm10_rmsk.gtf ....../count_T230_CD8R5pos_R1 ......./Velocyto/gencode.v32.primary_assembly.annotation.gtf
```

**My concatenated loom object:**
![Screenshot 2023-05-05 at 15 29 14](https://user-images.githubusercontent.com/62179082/236486648-edac67ef-8d4f-4973-b5e7-6ebbce3c2176.png)

![Screenshot 2023-05-05 at 15 29 51](https://user-images.githubusercontent.com/62179082/236486830-7a4074a1-348d-482b-b47d-6f992f616570.png)

![Screenshot 2023-05-05 at 16 51 05](https://user-images.githubusercontent.com/62179082/236506541-587eb411-4c1e-4814-8dd8-08b4585074e7.png)

![Screenshot 2023-05-05 at 17 05 01](https://user-images.githubusercontent.com/62179082/236509568-1b7f0e93-cdb3-4a53-a723-b9b9ae76dfff.png)

3. I did not merge the different individual loom objects to obtain the `count302_chrMTGTF_concat_adata`. I concatenated  with `count302_chrMTGTF_concat_adata = count302_R1_chrMTGTF_adata.concatenate([count302_R2_chrMTGTF_adata])`. From my workflow in (1), I only changed the cell barcodes of both loom object and Seurat object so that they matched. Then, I merged them with `scv.utils.merge`. Should I also subset the genes? Can you help me to subset the genes if I need to do that?

In https://github.com/theislab/scvelo/issues/215, I can use `adata = adata[list_of_barcodes].copy()` to subset the cells which I think `scv.utils.merge` took care of it. It is because Seurat object has 19,890 n_obs, concatenated loom has 24,640 n_obs, and the merged object has 19,890 n_obs. 

Thank you so much!

**Comment by WeilerP** [comment] 2023-05-05 16:37
> Do you know how to better check whether the values were raw or normalised because they are most just 0?

Just use modulo operation, _i.e._, something along the lines of

```
np.allclose(adata.X.data % 1, 0)
```

> Should I also subset the genes? Can you help me to subset the genes if I need to do that?

Subsetting is done internally. See [here](https://github.com/theislab/scvelo/blob/3b9fb0706fad9b49cb2e399b0326ae4b05042c24/scvelo/core/_anndata.py#L513-L518) and [here](https://github.com/theislab/scvelo/blob/3b9fb0706fad9b49cb2e399b0326ae4b05042c24/scvelo/core/_anndata.py#L528-L530).

Did the normalization work with the changes you made?

**Comment by WeilerP** [comment] 2023-05-05 16:39
> Merged Seurat-loom object still had very high unspliced %

Is the percentage similar to what you get when looking at the original LOOM files? I suppose not. If it's different, the issue comes from how you processed the data. I suggest you follow the normal scVelo workflow and preprocess the data based on the LOOM file using scVelo's function.

**Comment by denvercal1234GitHub** [comment] 2023-05-05 16:57
Hi @WeilerP, 

`np.allclose(SeuratloomObject.X.data % 1, 0)` returned `False`. So I think the data were indeed **_not_** normalised.

**Q1.** However, the unspliced % is still the same (65%) which is very high. **Do you think I did something wrong with the `velocyto run10x -m ....../Velocyto/mm10_rmsk.gtf ....../count_T230_CD8R5pos_R1 ......./Velocyto/gencode.v32.primary_assembly.annotation.gtf`?**


`scv.pp.filter_and_normalize(SeuratloomObject.X.data, min_shared_counts=30, n_top_genes=3000, retain_genes = clusteringFineTune_genes_list)` now returned:

```
Filtered out 11142 genes that are detected 30 counts (shared).
Normalized count data: X, spliced, unspliced.
Skip filtering by dispersion since number of variables are less than `n_top_genes`.
Logarithmized X.
```

**Q2.** Can I run differential kinetics test after I ran `scv.tl.recover_dynamics(SeuratloomObject.X.data)` and `scv.tl.velocity(SeuratloomObject.X.data, mode='dynamical')`? Or, I can only do differential kinetics test with `scv.tl.velocity(SeuratloomObject.X.data, mode='stochastic')`?

Thank you again for your help!

**Comment by WeilerP** [comment] 2023-05-05 17:28
> np.allclose(SeuratloomObject.X.data % 1, 0) returned False. So I think the input data were indeed not normalised.

Well if it returns False, the data is not whole counts. So the issue seems to be there and the function behaves as intended.

**Closed by WeilerP** 2023-05-05 17:28 UTC
Labels: bug

**Comment by denvercal1234GitHub** [comment] 2023-05-05 18:21
Hi @WeilerP. 

I reran the codes, and now the `np.allclose(mergedSeuratLoom.X)` returned `True` before normalization and `False` after normalisation. 

But, the unspliced % is still high over 60%, which is similarly high in the original loom objects before concatenation. Do you have some suggestions why? Would this high unspliced make the RNA Velocity inaccurate? 

And, with this high unspliced, can I run differential kinetics test after I ran scv.tl.recover_dynamics(SeuratloomObject) and scv.tl.velocity(SeuratloomObject, mode='dynamical')? 

Thank you for your help!

![Screenshot 2023-05-05 at 19 16 14](https://user-images.githubusercontent.com/62179082/236536664-f36250c0-577c-49c4-b745-4444aaae0bfb.png)
