### ISSUE TITLE
Corrupted neighbor graph

### ISSUE THREAD

**Issue by MatsuSui** [theislab/scvelo#888] opened 2022-06-18 05:19 UTC
Error when running scv.tl.velocity_graph() that prevents me from moving forward.And I have  removed the duplicate cells
scvelo==0.2.4 scanpy==1.9.1 anndata==0.7.8 numpy==1.21.6 matplotlib==3.5.1pandas==1.4.2 

```
scv.pp.filter_and_normalize(adata,min_shared_counts=30,n_top_genes=2000)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata,n_jobs=20)
scv.tl.velocity(adata, mode = "dynamical",n_jobs=20)
scv.tl.velocity_graph(adata,n_jobs=20)
scv.pl.velocity_embedding(adata, basis='X_tsne',arrow_size=5)
scv.pl.velocity_embedding_stream(adata, `basis='X_tsne',color='seurat_clusters',save='tsnescvelo.pdf')`
```

Filtered out 12921 genes that are detected 30 counts (shared).
WARNING: Did not normalize X as it looks processed already. To enforce normalization, set `enforce=True`.
Normalized count data: spliced, unspliced.
Extracted 7507 highly variable genes.
WARNING: Did not modify X as it looks preprocessed already.
computing neighbors
    finished (0:00:27) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
WARNING: The neighbor graph has an unexpected format (e.g. computed outside scvelo) 
or is corrupted (e.g. due to subsetting). Consider recomputing with `pp.neighbors`.
computing moments based on connectivities
    finished (0:00:17) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
recovering dynamics (using 20/96 cores)
100%
604/604 [04:12<00:00, 3.87s/gene]
    finished (0:04:52) --> added 
    'fit_pars', fitted parameters for splicing dynamics (adata.var)
computing velocities
    finished (0:00:25) --> added 
    'velocity', velocity vectors for each individual cell (adata.layers)
WARNING: The neighbor graph has an unexpected format (e.g. computed outside scvelo) 
or is corrupted (e.g. due to subsetting). Consider recomputing with `pp.neighbors`.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [36], in <cell line: 6>()
      4 scv.tl.recover_dynamics(adata,n_jobs=20)
      5 scv.tl.velocity(adata, mode = "dynamical",n_jobs=20)
----> 6 scv.tl.velocity_graph(adata,n_jobs=20)
      7 scv.pl.velocity_embedding(adata, basis='X_tsne',arrow_size=5)
      8 scv.pl.velocity_embedding_stream(adata, basis='X_tsne',color='seurat_clusters',save='tsnescvelo.pdf')
ValueError: Your neighbor graph seems to be corrupted. Consider recomputing via pp.neighbors.

**Comment by WeilerP** [comment] 2022-06-18 05:33
Seems like a duplicate of #637 (or #632, respectively). Please check that this is not the case. Happy to reopen if this this issue is different.

**Closed by WeilerP** 2022-06-18 05:33 UTC

**Comment by MatsuSui** [comment] 2022-06-18 05:46
Thank you for your reply. There is no duplicate observation in my data. I don't know the reason for corrupted neighbor graph.

adata.to_df().duplicated().sum()
0

**Comment by WeilerP** [comment] 2022-06-18 06:14
@MatsuSui, the data in `adata.X` looks already preprocessed, _i.e._ non integer counts. This causes `adata.X` to be neither normalized nor `log1p` transformed. How was the data preprocessed? To enforce normalization, you can pass `enforce=True`. If you want to `log1p` the data, you'll need to run `scanpy.pp.log1p` after `scv.pp.filter_and_normalize`.
The issue should also no longer exist when providing raw counts.

**Comment by MatsuSui** [comment] 2022-06-18 06:24
@WeilerP ,I used Seurat to deal with my data before performing scvelo, so the counts have been normalized. Either I skip the step "scv.pp.filter_and_normalize" or use "enforce=True" to enforce the data to be normalized again, the neighbor graph is still corrupeted.

**Comment by WeilerP** [comment] 2022-06-20 09:23
Have the counts only been normalized or also `log1p` transformed? If the former, you should manually `log1p` transform them.
If the data is already normalized/preprocessed, enforcing normalization does not make sense. I suggest you run the preprocessing directly in Python.
