### ISSUE TITLE
scvelo filtering issue 

### ISSUE THREAD

**Issue by oswaldbra12** [theislab/scvelo#204] opened 2020-05-28 19:04 UTC
When trying to filter data using the Alevin tutorial, I am coming across an error when trying to filter the data. I'll post the error below. I am at a loss of how to fix this and nobody has been able to help me solve this problem. 

```python
Code used: scv.pp.filter_and_normalize(adata)

Error: 

R[write to console]: Error in (function (object, connection, ascii = FALSE, xdr = TRUE, version = NULL,  :
  unimplemented type 'char' in 'eval'
 
---------------------------------------------------------------------------
RRuntimeError                             Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    160                     if reductor is not None:
--> 161                         rv = reductor(4)
    162                     else:
 
~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py in __getstate__(self)
    121             ser = rmemory.protect(
--> 122                 _rinterface.serialize(
    123                     self.__sexp__._cdata,
 
~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/rpy2/rinterface_lib/_rinterface_capi.py in serialize(cdata, cdata_env)
    412         if error_occured[0]:
--> 413             raise embedded.RRuntimeError(_geterrmessage())
    414         return res
 
RRuntimeError: Error in (function (object, connection, ascii = FALSE, xdr = TRUE, version = NULL,  :
  unimplemented type 'char' in 'eval'
 
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136
--> 137     d = id(x)
    138     y = memo.get(d, _nil)
 
SystemError: <built-in function id> returned a result with an error set
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136
--> 137     d = id(x)
    138     y = memo.get(d, _nil)
 
SystemError: <built-in function id> returned a result with an error set
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136
--> 137     d = id(x)
    138     y = memo.get(d, _nil)
 
SystemError: <built-in function id> returned a result with an error set
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136
--> 137     d = id(x)
    138     y = memo.get(d, _nil)
 
SystemError: <built-in function id> returned a result with an error set
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136
--> 137     d = id(x)
    138     y = memo.get(d, _nil)
 
SystemError: <built-in function id> returned a result with an error set
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136
--> 137     d = id(x)
    138     y = memo.get(d, _nil)
 
SystemError: <built-in function id> returned a result with an error set
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136
--> 137     d = id(x)
    138     y = memo.get(d, _nil)
 
SystemError: <built-in function id> returned a result with an error set
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136
--> 137     d = id(x)
    138     y = memo.get(d, _nil)
 
SystemError: <built-in function id> returned a result with an error set
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136
--> 137     d = id(x)
    138     y = memo.get(d, _nil)
 
SystemError: <built-in function id> returned a result with an error set
 
The above exception was the direct cause of the following exception:
 
SystemError                               Traceback (most recent call last)
<ipython-input-15-143c1fb66528> in <module>
----> 1 scv.pp.filter_and_normalize(adata)
      2
      3
      4
      5
 
~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/scvelo/preprocessing/utils.py in filter_and_normalize(data, min_counts, min_counts_u, min_cells, min_cells_u, min_shared_counts, min_shared_cells, n_top_genes, flavor, log, copy)
    452         logg.warn('Could not find spliced / unspliced counts.')
    453
--> 454     filter_genes(adata, min_counts=min_counts, min_counts_u=min_counts_u, min_cells=min_cells, min_cells_u=min_cells_u,
    455                  min_shared_counts=min_shared_counts, min_shared_cells=min_shared_cells,)
    456     normalize_per_cell(adata)
 
~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/scvelo/preprocessing/utils.py in filter_genes(data, min_counts, min_cells, max_counts, max_cells, min_counts_u, min_cells_u, max_counts_u, max_cells_u, min_shared_counts, min_shared_cells, copy)
    194             gene_subset &= filter(X, min_cells=_min_cells, max_cells=_max_cells)[0]
    195
--> 196         adata._inplace_subset_var(gene_subset)
    197
    198         s = np.sum(~gene_subset)
 
~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/anndata/_core/anndata.py in _inplace_subset_var(self, index)
   1214         Same as `adata = adata[:, index]`, but inplace.
   1215         """
-> 1216         adata_subset = self[:, index].copy()
   1217         self._init_as_actual(adata_subset, dtype=self._X.dtype)
   1218
 
~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/anndata/_core/anndata.py in __getitem__(self, index)
   1048         """Returns a sliced view of the object."""
   1049         oidx, vidx = self._normalize_indices(index)
-> 1050         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1051
   1052     def _remove_unused_categories(self, df_full, df_sub, uns):
 
~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/anndata/_core/anndata.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, obsp, varp, oidx, vidx)
    280             if not isinstance(X, AnnData):
    281                 raise ValueError("`X` has to be an AnnData object.")
--> 282             self._init_as_view(X, oidx, vidx)
    283         else:
    284             self._init_as_actual(
 
~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/anndata/_core/anndata.py in _init_as_view(self, adata_ref, oidx, vidx)
    328         self._varp = adata_ref.varp._view(self, vidx)
    329         # hackish solution here, no copy should be necessary
--> 330         uns_new = deepcopy(self._adata_ref._uns)
    331         # need to do the slicing before setting the updated self._n_obs, self._n_vars
    332         self._n_obs = self._adata_ref.n_obs  # use the original n_obs here
 
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):
 
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict
 
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    151             copier = getattr(x, "__deepcopy__", None)
    152             if copier is not None:
--> 153                 y = copier(memo)
    154             else:
    155                 reductor = dispatch_table.get(cls)
 
SystemError: <built-in method __deepcopy__ of numpy.ndarray object at 0x136c57e40> returned a result with an error set


#### Versions:
scvelo==0.2.0  scanpy==1.4.6  anndata==0.7.1  loompy==3.0.6  numpy==1.18.1  scipy==1.4.1  matplotlib==3.1.3  sklearn==0.22.1  pandas==1.0.3  WARNING: There is a newer scvelo version available on PyPI:
 Your version: 	 0.2.0 
 Latest version: 	 0.2.1

**Comment by k3yavi** [comment] 2020-05-28 20:24
I can second this bug.
https://github.com/COMBINE-lab/salmon/issues/526

**Comment by VolkerBergen** [comment] 2020-05-28 20:49
Seems to be an issue with copying subsetted anndata. 

Could you please run the following lines to narrow down the potential issue:
```
adata_sub = adata[:, :100]
print(adata_sub)
adata_new = adata_sub.copy()
```

**Comment by oswaldbra12** [comment] 2020-05-28 21:07
Thank you for your quick response. An error was generated when I ran the code you requested:

Code:
adata_sub = adata[:, :100]
print(adata_sub)
adata_new = adata_sub.copy()

Error: 
R[write to console]: Error in (function (object, connection, ascii = FALSE, xdr = TRUE, version = NULL,  : 
  unimplemented type 'char' in 'eval'

R[write to console]: In addition: 
R[write to console]: Warning message:

R[write to console]: call dbDisconnect() when finished working with a connection 

---------------------------------------------------------------------------
RRuntimeError                             Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    160                     if reductor is not None:
--> 161                         rv = reductor(4)
    162                     else:

~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py in __getstate__(self)
    121             ser = rmemory.protect(
--> 122                 _rinterface.serialize(
    123                     self.__sexp__._cdata,

~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/rpy2/rinterface_lib/_rinterface_capi.py in serialize(cdata, cdata_env)
    412         if error_occured[0]:
--> 413             raise embedded.RRuntimeError(_geterrmessage())
    414         return res

RRuntimeError: Error in (function (object, connection, ascii = FALSE, xdr = TRUE, version = NULL,  : 
  unimplemented type 'char' in 'eval'


The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-17-40bbcb8504c6> in <module>
----> 1 adata_sub = adata[:, :100]
      2 print(adata_sub)
      3 adata_new = adata_sub.copy()

~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/anndata/_core/anndata.py in __getitem__(self, index)
   1048         """Returns a sliced view of the object."""
   1049         oidx, vidx = self._normalize_indices(index)
-> 1050         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1051 
   1052     def _remove_unused_categories(self, df_full, df_sub, uns):

~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/anndata/_core/anndata.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, obsp, varp, oidx, vidx)
    280             if not isinstance(X, AnnData):
    281                 raise ValueError("`X` has to be an AnnData object.")
--> 282             self._init_as_view(X, oidx, vidx)
    283         else:
    284             self._init_as_actual(

~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/anndata/_core/anndata.py in _init_as_view(self, adata_ref, oidx, vidx)
    328         self._varp = adata_ref.varp._view(self, vidx)
    329         # hackish solution here, no copy should be necessary
--> 330         uns_new = deepcopy(self._adata_ref._uns)
    331         # need to do the slicing before setting the updated self._n_obs, self._n_vars
    332         self._n_obs = self._adata_ref.n_obs  # use the original n_obs here

~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    151             copier = getattr(x, "__deepcopy__", None)
    152             if copier is not None:
--> 153                 y = copier(memo)
    154             else:
    155                 reductor = dispatch_table.get(cls)

SystemError: <built-in method __deepcopy__ of numpy.ndarray object at 0x1379f3300> returned a result with an error set

**Comment by VolkerBergen** [comment] 2020-05-28 21:26
ok, interesting - so already fails with subsetting.

now plz run:
```
print(adata)
adata = adata.copy()
adata_sub = adata[:, :100]
```

**Comment by VolkerBergen** [comment] 2020-05-28 21:40
and if that won't work, please try:
```
del adata.uns
adata_sub = adata[:, :100]
```

**Comment by oswaldbra12** [comment] 2020-05-28 21:46
Code:
print(adata)
adata = adata.copy()
adata_sub = adata[:, :100]


Result:

R[write to console]: Error in (function (object, connection, ascii = FALSE, xdr = TRUE, version = NULL,  : 
  unimplemented type 'char' in 'eval'

AnnData object with n_obs × n_vars = 2325 × 54448 
    obs: 'sizeFactor'
    uns: 'tximetaInfo', 'quantInfo', 'countsFromAbundance', 'level', 'txomeInfo', 'txdbInfo'
    obsm: 'X_pca', 'X_tsne'
    layers: 'spliced', 'unspliced', 'logcounts'
---------------------------------------------------------------------------
RRuntimeError                             Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    160                     if reductor is not None:
--> 161                         rv = reductor(4)
    162                     else:

~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py in __getstate__(self)
    121             ser = rmemory.protect(
--> 122                 _rinterface.serialize(
    123                     self.__sexp__._cdata,

~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/rpy2/rinterface_lib/_rinterface_capi.py in serialize(cdata, cdata_env)
    412         if error_occured[0]:
--> 413             raise embedded.RRuntimeError(_geterrmessage())
    414         return res

RRuntimeError: Error in (function (object, connection, ascii = FALSE, xdr = TRUE, version = NULL,  : 
  unimplemented type 'char' in 'eval'


The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    136 
--> 137     d = id(x)
    138     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-21-e298c7a64817> in <module>
      1 print(adata)
----> 2 adata = adata.copy()
      3 adata_sub = adata[:, :100]

~/opt/anaconda3/envs/py38/lib/python3.8/site-packages/anndata/_core/anndata.py in copy(self, filename)
   1441                 uns=self.uns.copy()
   1442                 if isinstance(self.uns, DictView)
-> 1443                 else deepcopy(self.uns),
   1444                 obsm=self.obsm.copy(),
   1445                 varm=self.varm.copy(),

~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

~/opt/anaconda3/envs/py38/lib/python3.8/copy.py in deepcopy(x, memo, _nil)
    151             copier = getattr(x, "__deepcopy__", None)
    152             if copier is not None:
--> 153                 y = copier(memo)
    154             else:
    155                 reductor = dispatch_table.get(cls)

SystemError: <built-in method __deepcopy__ of numpy.ndarray object at 0x1379f3300> returned a result with an error set

Follow on:

code:
del adata.uns
adata_sub = adata[:, :100]

This seems to have fixed the issue and has allowed me to move forward. It currently is performing the recover dynamics line. 

What seemed to be the issue?

**Comment by VolkerBergen** [comment] 2020-05-28 21:56
The issue is with deeopcopy unstructured annotations from adata.uns.

Could you also `print(adata.uns)` right after reading the data? That brings us closer to the root of the issue now.

**Comment by oswaldbra12** [comment] 2020-05-28 21:57
OrderedDict([('neighbors', {'connectivities_key': 'connectivities', 'distances_key': 'distances', 'indices': array([[   0,  194,  173, ...,  762,  164,  325],
       [   1,  206,  420, ...,  230,  411,   66],
       [   2,  192,  414, ...,  337,  282,   74],
       ...,
       [2322, 1332, 1805, ..., 2181, 1599, 1616],
       [2323, 2172, 1188, ..., 1323, 1148, 1472],
       [2324, 2266, 2247, ..., 1821, 2029, 2026]]), 'params': {'n_neighbors': 30, 'method': 'umap', 'metric': 'euclidean', 'n_pcs': 30}}), ('recover_dynamics', {'fit_connected_states': True, 'fit_basal_transcription': None, 'use_raw': False}), ('velocity_settings', {'mode': 'dynamical', 'fit_offset': False, 'perc': [5, 95], 'embeddings': ['tsne']}), ('velocity_graph', <2325x2325 sparse matrix of type '<class 'numpy.float32'>'
	with 185067 stored elements in Compressed Sparse Row format>), ('velocity_graph_neg', <2325x2325 sparse matrix of type '<class 'numpy.float32'>'
	with 162235 stored elements in Compressed Sparse Row format>)])

**Comment by VolkerBergen** [comment] 2020-05-28 21:58
I meant right after reading the data before running all the other lines.

**Comment by oswaldbra12** [comment] 2020-05-28 21:59
My apologies:
Result: 
OrderedDict()

**Comment by VolkerBergen** [comment] 2020-05-28 22:03
Nope, that's still not it ;) did you print right after re-reading the adata? 

It should have had somewhat like what you got before. 
uns: 'tximetaInfo', 'quantInfo', 'countsFromAbundance', 'level', 'txomeInfo', 'txdbInfo'

**Comment by oswaldbra12** [comment] 2020-05-28 22:13
So, I'm a novice at this but I think this is what you want.
When I **print(adata.uns)** after adata I get this:

Code:
adata
print(adata.uns)

Result:
{'tximetaInfo': R object with classes: ('list',) mapped to:
[ListSexpVector, FloatSexpVector]
  version: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x133811600> [RTYPES.VECSXP]
  importTime: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x1338114c0> [RTYPES.REALSXP], 'quantInfo': R object with classes: ('list',) mapped to:
[StrSexpVe..., StrSexpVe..., StrSexpVe..., ListSexpV..., ..., FloatSexp..., StrSexpVe..., StrSexpVe..., StrSexpVe...]
  salmon_version: <class 'numpy.ndarray'>
  array(['1.2.0'], dtype='<U5')
  samp_type: <class 'numpy.ndarray'>
  array(['none'], dtype='<U4')
  opt_type: <class 'numpy.ndarray'>
  array(['em'], dtype='<U2')
R object with classes: ('list',) mapped to:
[StrSexpVe..., StrSexpVe..., StrSexpVe..., ListSexpV..., ..., FloatSexp..., StrSexpVe..., StrSexpVe..., StrSexpVe...]
...
  library_types: <class 'numpy.ndarray'>
  array([44.79765771])
  frag_dist_length: <class 'numpy.ndarray'>
  array(['quant'], dtype='<U5')
  seq_bias_correct: <class 'numpy.ndarray'>
  array(['Wed May 13 10:41:53 2020'], dtype='<U24')
  gc_bias_correct: <class 'numpy.ndarray'>
  array(['Wed May 13 11:06:43 2020'], dtype='<U24'), 'countsFromAbundance': array(['no'], dtype='<U2'), 'level': array(['gene'], dtype='<U4'), 'txomeInfo': R object with classes: ('list',) mapped to:
[StrSexpVe..., StrSexpVe..., StrSexpVe..., StrSexpVe..., ..., ListSexpV..., StrSexpVe..., StrSexpVe..., BoolSexpV...]
  index: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x133811600> [RTYPES.STRSXP]
  source: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x133811d40> [RTYPES.STRSXP]
  organism: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x133811540> [RTYPES.STRSXP]
  release: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x1338111c0> [RTYPES.STRSXP]
  genome: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x133811600> [RTYPES.STRSXP]
  fasta: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x1338111c0> [RTYPES.VECSXP]
  gtf: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x133811880> [RTYPES.STRSXP]
  sha256: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x133811540> [RTYPES.STRSXP]
  linkedTxome: <class 'rpy2.rinterface.BoolSexpVector'>
  <rpy2.rinterface.BoolSexpVector object at 0x133811600> [RTYPES.LGLSXP], 'txdbInfo': array(['TxDb', 'GenomicFeatures',
       '/Volumes/projects_secondary/mnp/brandon/alvin_velocity_workflow/reference_genome/gencode.vM24.annotation.expanded.gtf',
       NA_character_, NA_character_, NA_character_, NA_character_,
       '842873', 'GenomicFeatures package from Bioconductor',
       '2020-05-27 14:54:01 -0400 (Wed, 27 May 2020)', '1.40.0', '2.2.0',
       '1.2'], dtype=object)}

**Comment by VolkerBergen** [comment] 2020-05-29 06:03
Yes, so there's all kinds of unstructured annotations mainly from rpy2 that anndata cannot handle. Those are not of any use and can be safely deleted. Ideally, anndata should internally check for disrupted annotations. Could you quickly use the source version of anndata `pip install git+https://github.com/theislab/anndata`, re-read and try subsetting again `adata[:, :100]`? 
If that still gives the same error, I'll add some verification tests in scvelo to make sure this gets caught and 'repaired'.

**Comment by VolkerBergen** [comment] 2020-05-29 06:11
@flying-sheep when we got unstructured annotation types that are not acceptable/handable (see above), where should this ideally be caught? - already when reading, or add some verification test afterwards?

**Comment by oswaldbra12** [comment] 2020-05-29 15:04
I have done as you ask and still no luck :(  Still getting the same error.

**Comment by VolkerBergen** [comment] 2020-05-29 16:11
Alright, thanks - so on the anndata side this still needs to be addressed.

The latest scvelo commit should solve it now (at least in a temporary way). Install the latest version via `pip install git+https://github.com/theislab/scvelo`.

Would appreciate, if you could let me know whether that fixes it.

**Comment by brejnev** [comment] 2020-05-30 11:12
I had same problem. It seems fixed on my side. Thanks.

**Comment by oswaldbra12** [comment] 2020-05-30 11:16
Yes, this solved my problem and all the lines seemed to run successfully. Thank you.

**Closed** 2020-06-05 23:45 UTC
Labels: anndata
