### ISSUE TITLE
Running scv.pp.neighbours does not correct corruption

### ISSUE THREAD

**Issue by pranzatelli** [theislab/scvelo#901] opened 2022-07-13 20:19 UTC
`scv.pp.moments` returns a warning that the neighbor graph is corrupted (most likely because I ran `sc.ex.pp.bbknn` beforehand) and suggests running `scv.pp.neighbors`. Doing so does not correct the error.

```python
scv.pp.neighbors(adata)
scv.pp.moments(adata)
```

<details>

<summary> Error output </summary>

```pytb
computing neighbors
scv.pp.moments(adataSG)
    finished (0:00:10) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
WARNING: The neighbor graph has an unexpected format (e.g. computed outside scvelo) 
or is corrupted (e.g. due to subsetting). Consider recomputing with `pp.neighbors`.
computing moments based on connectivities
    finished (0:00:20) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
```
</details>

<details> <summary> Versions </summary>

```pytb
scvelo==0.2.4  scanpy==1.7.2  anndata==0.8.0  loompy==3.0.7  numpy==1.21.2  scipy==1.6.3  matplotlib==3.4.2  sklearn==0.24.2  pandas==1.2.4
```
</details>

**Comment by pranzatelli** [comment] 2022-07-13 21:16
I will add - #632 and #637 don't apply as I am not using SIRV data, and #256 and #888 don't have an answer relevant to my situation.

**Comment by WeilerP** [comment] 2022-07-14 06:12
@pranzatelli, just to double check: Did you verify that there are no duplicates (after the filtering/normalization) in your data?

If so, would you please check if
1. `"neighbors"` is in `adata.uns.keys()` and `"params"` in `adata.uns["neighbors"]`? This should be since you are calculating it with Scanpy/scVelo.
2. If there are no true duplicates after filtering/normalization, I suppose the issue is numerical. You can check if the following statement is true:
```python
n_neighs = (get_neighs(adata, "distances") > 0).sum(1)
n_neighs.min() * 2 > n_neighs.max()
```
If the latter is the case, I would not worry about it. It's just a heuristic (which will most likely be removed in the future to not have this kind of issue pop up).

**Comment by WeilerP** [comment] 2022-07-25 06:04
@pranzatelli, any news on this? I'll close this for now. Happy to reopen if needed.

**Closed by WeilerP** 2022-07-25 06:04 UTC

**Comment by pranzatelli** [comment] 2022-07-27 18:46
Yes, this should be closed. It looks like I'm running into a filtering problem with loompy upstream of this, and have very few cells to work with. Thank you for your help!
