### ISSUE TITLE
`StopIteration`, `scv.pl.velocity` can't plot velocity when the `mode="dynamical"`

### ISSUE THREAD

**Issue by danli349** [theislab/scvelo#1033] opened 2023-03-30 17:39 UTC
Hello:

When I run `scv.pl.velocity` I found this error:

```
scv.tl.velocity(adata, mode="dynamical", vkey='velocity')
scv.pl.velocity(adata, 
                var_names = 'Itgb1', 
                color='leiden_r0.3',
                ncols=3,
                color_map = ['coolwarm', 'coolwarm'],
                alpha=1,
               save = './figures/Itgb1_dKO_only.pdf')
```

```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
Cell In[114], line 1
----> 1 scv.pl.velocity(adata, 
      2                 var_names = 'Itgb1', 
      3                 color='leiden_r0.3',
      4                 ncols=3,
      5                 color_map = ['coolwarm', 'coolwarm'],
      6                 alpha=1,
      7                save = './figures/Itgb1_dKO_only.pdf')

File ~/miniconda3/lib/python3.8/site-packages/scvelo/plotting/velocity.py:203, in velocity(adata, var_names, basis, vkey, mode, fits, layers, color, color_map, colorbar, perc, alpha, size, groupby, groups, legend_loc, legend_fontsize, use_raw, fontsize, figsize, dpi, show, save, ax, ncols, **kwargs)
    201     if isinstance(color_map, (list, tuple)):
    202         cmap = color_map[-1] if layer in ["X", skey] else color_map[0]
--> 203     scatter(
    204         adata,
    205         basis=basis,
    206         color=var,
    207         layer=layer,
    208         title=title,
    209         color_map=cmap,
    210         alpha=alpha,
    211         frameon=False,
    212         show=False,
    213         ax=ax,
    214         save=False,
    215         **scatter_kwargs,
    216         **kwargs,
    217     )
    219 if mode == "stochastic":
    220     ss, us = second_order_moments(_adata)

File ~/miniconda3/lib/python3.8/site-packages/scvelo/plotting/scatter.py:614, in scatter(adata, basis, x, y, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_loc_lines, legend_fontsize, legend_fontweight, legend_fontoutline, legend_align_text, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, add_density, add_assignments, add_linfit, add_polyfit, add_rug, add_text, add_text_pos, add_margin, add_outline, outline_width, outline_color, n_convolve, smooth, normalize_data, rescale_color, color_gradients, dpi, frameon, zorder, ncols, nrows, wspace, hspace, show, save, ax, **kwargs)
    611             kwargs["s"] = np.array(kwargs["s"])[order]
    613 marker = kwargs.pop("marker", ".")
--> 614 smp = ax.scatter(
    615     x, y, c=c, alpha=alpha, marker=marker, zorder=zorder, **kwargs
    616 )
    618 outline_dtypes = (list, tuple, np.ndarray, int, np.int_, str)
    619 if isinstance(add_outline, outline_dtypes) or add_outline:

File ~/miniconda3/lib/python3.8/site-packages/matplotlib/__init__.py:1423, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1420 @functools.wraps(func)
   1421 def inner(ax, *args, data=None, **kwargs):
   1422     if data is None:
-> 1423         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1425     bound = new_sig.bind(ax, *args, **kwargs)
   1426     auto_label = (bound.arguments.get(label_namer)
   1427                   or bound.kwargs.get(label_namer))

File ~/miniconda3/lib/python3.8/site-packages/matplotlib/axes/_axes.py:4538, in Axes.scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, edgecolors, plotnonfinite, **kwargs)
   4535 if edgecolors is None:
   4536     orig_edgecolor = kwargs.get('edgecolor', None)
   4537 c, colors, edgecolors = \
-> 4538     self._parse_scatter_color_args(
   4539         c, edgecolors, kwargs, x.size,
   4540         get_next_color_func=self._get_patches_for_fill.get_next_color)
   4542 if plotnonfinite and colors is None:
   4543     c = np.ma.masked_invalid(c)

File ~/miniconda3/lib/python3.8/site-packages/matplotlib/axes/_axes.py:4336, in Axes._parse_scatter_color_args(c, edgecolors, kwargs, xsize, get_next_color_func)
   4329 if c is None:
   4330     c = (facecolors if facecolors is not None
   4331          else "b" if mpl.rcParams['_internal.classic_mode']
   4332          else get_next_color_func())
   4333 c_is_string_or_strings = (
   4334     isinstance(c, str)
   4335     or (np.iterable(c) and len(c) > 0
-> 4336         and isinstance(cbook._safe_first_finite(c), str)))
   4338 def invalid_shape_exception(csize, xsize):
   4339     return ValueError(
   4340         f"'c' argument has {csize} elements, which is inconsistent "
   4341         f"with 'x' and 'y' with size {xsize}.")

File ~/miniconda3/lib/python3.8/site-packages/matplotlib/cbook/__init__.py:1749, in _safe_first_finite(obj, skip_nonfinite)
   1746     raise RuntimeError("matplotlib does not "
   1747                        "support generators as input")
   1748 else:
-> 1749     return next(val for val in obj if safe_isfinite(val))

StopIteration: 
```

This error did not show when the mode="stochastic":
```
scv.tl.velocity(adata, mode="stochastic", vkey='velocity')
scv.pl.velocity(adata, 
                var_names = 'Itgb1', 
                color='leiden_r0.3',
                ncols=3,
                color_map = ['coolwarm', 'coolwarm'],
                alpha=1,
               save = './figures/Itgb1_dKO_only.pdf')
```

![image](https://user-images.githubusercontent.com/33963919/228919602-cfff0ca8-a258-4696-9165-ac0b3f751d91.png)

Can someone let me know how to fix this error?
Thanks a lot!

**Comment by WeilerP** [comment] 2023-04-15 17:46
Closing this since package versions are not provided.

**Closed by WeilerP** 2023-04-15 17:46 UTC
Labels: bug

**Comment by KforKuma** [comment] 2023-12-25 06:12
I reproduced this problem on my server of centos 6, my environment is:

> matplotlib               3.7.0
> matplotlib-inline        0.1.6
> scanpy                   1.9.6
> scikit-learn             1.1.3
> scipy                    1.11.4
> scvelo                   0.3.1
> scvi-tools               1.0.4

The way to reproduce it is very simple, I used `>>> scv.pl.velocity(matching_velo, ['CD68','C1QA', 'S100A8', 'IL1B', 'TNF','CXCL8'],ncols=2,save=/figures/Myeloid/GeneList1_embed_UMAP.png')
`
