### ISSUE TITLE
problem for merging ldata and adata 

### ISSUE THREAD

**Issue by dahun73** [theislab/scvelo#1002] opened 2023-02-13 10:44 UTC
Hello :)

I'm trying to analyze RNA velocity using scvelo.
Actually,  I processed all of my data using 'Seurat' package before running scVelo. After that, I estimated RNA velocity using 'velocyto'. 

So, I want to merge those two data(already processed data(adata) and newly generated velocyto data(ldata)). Because "adata" has been already processed using "Seurat", the dimension of data set is different from ldata. After merging those two data, as a result, there was a error like this:

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/tmp/ipykernel_2295160/216160399.py in <module>
----> 1 adata = scv.utils.merge(adata,ldata)

~/anaconda3/lib/python3.9/site-packages/scvelo/core/_anndata.py in merge(adata, ldata, copy, **kwargs)
    524         if "id_length" in kwargs:
    525             id_length = kwargs.get("id_length")
--> 526         clean_obs_names(adata, id_length=id_length)
    527         clean_obs_names(ldata, id_length=id_length)
    528         common_obs = adata.obs_names.intersection(ldata.obs_names)

UnboundLocalError: local variable 'id_length' referenced before assignment
```

In this case, are there any tips for curating those two data? I think this error came from difference of those two data.
Frankly speaking, I'm not familiar with python language. If it can be basic question, I'm sorry for that... T.T

Thank you in advance!!!

**Comment by WeilerP** [comment] 2023-02-13 11:43
Duplicate of https://github.com/theislab/scvelo/issues/983. Please search open issues first, do not open a duplicate one, and use the issue template for bugs.

**Closed by WeilerP** 2023-02-13 11:43 UTC

**Comment by dahun73** [comment] 2023-02-13 11:59
@WeilerP  Thank you so much!
