### ISSUE TITLE
scv.pp.moments(adata)    AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32

### ISSUE THREAD

**Issue by shijianasdf** [theislab/scvelo#633] opened 2021-08-14 01:30 UTC
...

I use the demo data from Pancreatic endocrinogenesis and I run scv.pp.moments() 
```python 
  scv.pp.moments(adata) 
```

then i got the following error: 
```python
Traceback (most recent call last):
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/lowering.py", line 328, in lower_inst
    self.storevar(val, inst.target.name)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/lowering.py", line 1278, in storevar
    raise AssertionError(msg)
AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/scvelo/preprocessing/moments.py", line 64, in moments
    neighbors(
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/scvelo/preprocessing/neighbors.py", line 163, in neighbors
    neighbors.compute_neighbors(
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/scanpy/neighbors/__init__.py", line 808, in compute_neighbors
    self._distances, self._connectivities = _compute_connectivities_umap(
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/scanpy/neighbors/__init__.py", line 387, in _compute_connectivities_umap
    from umap.umap_ import fuzzy_simplicial_set
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/umap/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/umap/umap_.py", line 54, in <module>
    from umap.layouts import (
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/umap/layouts.py", line 39, in <module>
    def rdist(x, y):
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/decorators.py", line 221, in wrapper
    disp.compile(sig)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 106, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler.py", line 395, in _compile_core
    raise e
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/typed_passes.py", line 463, in run_pass
    NativeLowering().run_pass(state)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/typed_passes.py", line 384, in run_pass
    lower.lower()
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Storing i64 to ptr of i32 ('dim'). FE type int32
File "venv/lib/python3.9/site-packages/umap/layouts.py", line 52:
def rdist(x, y):
    <source elided>
    result = 0.0
    dim = x.shape[0]
    ^
During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at /Users/biofly/PycharmProjects/scVelo/venv/lib/python3.9/site-packages/umap/layouts.py (52)
```

#### Versions:

```
scvelo==0.2.3  scanpy==1.8.1  anndata==0.7.6  loompy==3.0.6  numpy==1.21.1  scipy==1.7.1  matplotlib==3.4.2  sklearn==0.24.2  pandas==1.3.1  
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.
```
>

**Comment by WeilerP** [comment] 2021-08-14 06:24
Closing as this is a duplicate of #388 (see also e.g. #428 and #570).

**Closed by WeilerP** 2021-08-14 06:24 UTC
Labels: bug, duplicate
