### ISSUE TITLE
scvelo.pl.velocity  without velocity graph for some genes

### ISSUE THREAD

**Issue by semir2** [theislab/scvelo#425] opened 2021-04-15 01:13 UTC
Hi, Thanks for great tool, it helped me a lot. Now I have a problem fro ploting, when I want to show key genes for transation of  direct with function of scvelo.pl.velocity, most genes have been showed right way, but one gene showed no velocity graph, I do not know why and could you tell me what happened to this?
![image](https://user-images.githubusercontent.com/46958122/114799673-c2acef00-9dca-11eb-8061-3814daee0871.png)

**Comment by WeilerP** [comment] 2021-05-28 13:19
@semir2, sorry for the late reply. Did you manage to fix the problem? If so, what was the cause? If not, could you provide reproducible example? Otherwise, with the limited information given, I'm not sure I can help investigating the issue.

**Comment by WeilerP** [comment] 2021-07-05 05:15
Closing this for now. Happy to reopen.

**Closed by WeilerP** 2021-07-05 05:15 UTC
Labels: awaiting response, bug
